### ISSUE TITLE
 ExtentHtmlReporter can't create the report.html

### ISSUE THREAD

**Issue by bly1201** [extent-framework/extentreports-csharp#103]
Hello All, 
Please help!!
I try to use the  ExtentHtmlReporter to create a costume report name like "MyReport.html" but it generate an "index.html" file instead.
By the way I'm using ExtentReports 4.1.0. and C# in VS 2019.
Here is my code

                //var htmlReporter = new ExtentHtmlReporter("C:\\DevEnvironment\\MyReport.html");
               var htmlReporter = new ExtentHtmlReporter(@"C:\DevEnvironment\MyReport.html");
                htmlReporter.Config.Theme = Theme.Standard;
                htmlReporter.Config.DocumentTitle = "My Test Report";
                htmlReporter.Config.ReportName = "Positive and Negative Test";
                _extent.AddSystemInfo("Environment", "OS Widows");
                _extent.AddSystemInfo("User Name", "Qlee");
                _extent.AttachReporter(htmlReporter);

 Thanks for your help.

**Comment by bly1201** [comment]
@dod0o This is the expected behavior with the version4 HtmlReporter. It creates upto 4 files depending upon the attributes that are created. This is also true for all new version4 reporters, to maximize performance and obviously to keep each file focused on its specific tasks.

If you would like the old behavior, use the version3 port of HtmlReporter:

var v3html = new ExtentV3HtmlReporter()

**Comment by Overclock303** [comment]
You can use the single and free-named old system with Version 4 HtmlReporter like this :
reporter = new ExtentHtmlReporter(path,ViewStyle.SPA);

Note that ViewStyle is a new feature of V4 reporter.
