### ISSUE TITLE
Problem with Enabling Timeline

### ISSUE THREAD

**Issue by gitvaibhavcodes** [extent-framework/extentreports-csharp#113]
I tried to set the Config.EnableTimeline to true, as we set Config.JS, etc. values but the timeline just doesn't appear.

**Comment by Moshex** [comment]
Seeing the same issue, not sure how to fix it.

**Comment by namilkimfree** [comment]
it's Uppercase when timeline.toString() but timeline display condition is  timeline == true 

I will be fix this issue wait please.

**Comment by namilkimfree** [comment]
https://github.com/namilkimfree/extentreports-csharp fork version fixed issue.

nuget download path is
You can use https://www.nuget.org/packages/ExtentReports.BugFix/4.2.2 or higher.

**Comment by anshooarora** [comment]
In version 5 (currently in alpha), the usage is following to enable/disable this feature:

```csharp
var extent = new ExtentReports();
var spark = new ExtentSparkReporter("Spark.html");
spark.Config.TimelineEnabled = true;
```

You can refer to the docs here:  https://www.extentreports.com/docs/versions/5/net/index.html
