### ISSUE TITLE
RemoveTest(ExtentTest) doesn't remove the test from the extent report

### ISSUE THREAD

**Issue by sszemer** [extent-framework/extentreports-csharp#115]
found similar issue in java repo:
https://github.com/anshooarora/extentreports-java/issues/1122

`
            htmlReporter = new ExtentHtmlReporter(reportPath);
            htmlReporter.Config.DocumentTitle = reportTitle;
            extent = new ExtentReports(); //todo podpiecie klov - statistics
            AddTestInfo("OS", new ComputerInfo().OSFullName);
            extent.AttachReporter(htmlReporter);
            extent.AnalysisStrategy = AnalysisStrategy.BDD;
            featureName = extent.CreateTest<Feature>(title);
            scenario = featureName.CreateNode<Scenario>(title);
            extent.RemoveTest(scenario);
`

The scenario appears as passed on report instead of being removed (second scenario)

![image](https://user-images.githubusercontent.com/14896512/105215384-81050300-5b51-11eb-89dd-089cc679d863.png)

Environment Details
ExtentReport Version : 4.1.0
Language: .net472
Editor: VS2019Pro
Testing Framework: NUnit + SpecFlow
Operating System and version: Windows 10 Pro

**Comment by namilkimfree** [comment]
there are not clearing it via recursive calls.
So, you need to call remove in the added Test.   

ex:
` featureName.RemoveTest(scenario)`

**Comment by srigor** [comment]
> there are not clearing it via recursive calls.
> So, you need to call remove in the added Test.
> 
> ex:
> ` featureName.RemoveTest(scenario)`

I'm having this issue as well, and your solution does not seem to work either. Calling `RemoveTest` from the ExtentReports object and passing the child ExtentTest node, or calling `RemoveNode` from the parent ExtentTest object and passing the child ExtentTest node does not work; in both cases the child node that was attempted to be removed still got written to the report.

**Comment by namilkimfree** [comment]
I have confirmed this problem.

If added, it will be added to the report
If it is removed, it is not removed from the report.

If the issue is fixed, we will share it.

**Comment by namilkimfree** [comment]
https://github.com/namilkimfree/extentreports-csharp  fork version fixed issue.

**Comment by anshooarora** [comment]
Please try with the latest version 5 alpha build.

https://www.nuget.org/packages/ExtentReports/5.0.0-alpha5

Docs https://www.extentreports.com/docs/versions/5/net/index.html#remove-tests

**Comment by srigor** [comment]
> Please try with the latest version 5 alpha build.
> 
> https://www.nuget.org/packages/ExtentReports/5.0.0-alpha5
> 
> Docs https://www.extentreports.com/docs/versions/5/net/index.html#remove-tests

Thanks for the fix on this. Unfortunately, myself as well as the original reporter of this issue appear to be on the 4.1.0 build of ExtentReports. So we have to get the paid version to get the bug fix for this?

**Comment by namilkimfree** [comment]
No, it is free version
You can try Install-Package ExtentReports -Version 5.0.0-alpha5  - - yourProjectName

or 
1. Right click and open the nuget manage  at your project 
2. Update tab click
3. Pre release check box check
4. Installed extentreports click
5. Update version selexted 5.0.0-alpha5 on update dropdown menu
6. Update click
