### ISSUE TITLE
Question, Is there a way to hide the "Features" Chart and "Features" percent? 

### ISSUE THREAD

**Issue by Moshex** [extent-framework/extentreports-csharp#116]
I have an issue with "Stake Holders" in my company not understanding the "Features" Graph. They feel that the graph is misleading since the report seems to imply that the whole feature has failed when in truth it's just a test within that feature that has failed. is there a way to hide the "Feature"  information on the dashboard or add information to the graph about what it really means?
![Untitled](https://user-images.githubusercontent.com/6087936/105555673-25f51c80-5cc7-11eb-959b-4d0be5b7e196.png)

**Comment by namilkimfree** [comment]
@Moshex  Do you want that feature?


Its function is
Feature, Scenario, and Step charts can be expanded and collapsed.


![image](https://user-images.githubusercontent.com/44854923/109481706-6fa00680-7ac0-11eb-9484-ffcea11d0d7f.png)

**Comment by namilkimfree** [comment]
https://github.com/namilkimfree/extentreports-csharp  fork version fixed issue.

**Comment by Moshex** [comment]
okay cool I will get the latest and see if it's there

**Comment by Moshex** [comment]
@namilkimfree I tried to update Extentreports to version 5.9.4 Alpha but it seems it's not compatible with .NET 
Framework 4.8 will it work with that framework in the future?

**Comment by namilkimfree** [comment]
@Moshex 

My forked nuget package version is 4.2.3 Please check the address below. 

https://www.nuget.org/packages/ExtentReports.BugFix/

**Comment by Moshex** [comment]
@namilkimfree  That worked, Thank you! now is there a way in code to make it collapsed by default?

**Comment by namilkimfree** [comment]
@Moshex  Yes, there is a way. You can do it like this:

```
var htmlReporter = new ExtentHtmlReporter(Path.Combine(path));
// default value is none
htmlReporter.Config.DashboardStyle = DashboardStyle.AccordionChart; 
```

**Comment by namilkimfree** [comment]
@Moshex  

In the next version we'll add code to make it collapsed by default.

**Comment by Moshex** [comment]
Sounds good thank you! as long as we have the option.

**Comment by anshooarora** [comment]
@Moshex With version 5, to hide the Features graph and also cascade the view changes to other graphs, the following JS can be used in the scripts section of `config.xml` or `config.json`.

```
$('.card-title:contains("Features")')
    .closest('.row')
    .children().toggleClass('col-md-4 col-md-6')
    .first().hide();
```

```xml
<!-- config.xml -->
<scripts>
  <![CDATA[
     $('.card-title:contains("Features")')
      .closest('.row')
      .children().toggleClass('col-md-4 col-md-6')
      .first().hide();
  ]]>
</scripts>
```

**Comment by anshooarora** [comment]
@namilkimfree  Thank you for your contributions.  I am working on version 5, would you like to contribute to it as well?  I would be pushing the source code this coming week (still working on a few pending items).

**Comment by namilkimfree** [comment]
@anshooarora  of course.  I would like to contribute to version 5.
