### ISSUE TITLE
Question, Does Extent Report supports test report with nUnit Parallelizable attribute?

### ISSUE THREAD

**Issue by samchughtai** [extent-framework/extentreports-csharp#118]
I am trying to generate an Extent HTML report on my nUnit .Net Core project. If the tests run in sequence then the report is properly generated but in case I add a parallelizable attribute the report is not generated at all? In Java TestNG I used TestListerners and it worked flawlessly. Can you please let me know if it is even possible in C#?

**Comment by anshooarora** [comment]
@samchughtai Yes, but the usage would be different to ensure your methods are properly synchronized to log to the relevant tests.
