### ISSUE TITLE
UI issue with pass/fail icons on ExtentHtmlReporter when test name is long

### ISSUE THREAD

**Issue by srigor** [extent-framework/extentreports-csharp#125]
Using the ExtentReports 4.1.0 version with dotnet core and the `ExtentHtmlReporter`, found that the formatting is strange on the html report when test names are long.

In this screenshot example, a data-driven test is being ran by csv file, and we're adding some of the csv row data to the test name to distinguish between iterations of the test method, causing the test name in the report to be more than one line. The pass/fail icons no longer match up to the child tests in the UI when this happens.

I'm not sure exactly how many characters it takes in the test name for this to start happening. Screen resolution does seem to matter, and this screenshot snippet was taken on a 1920x1080 resolution with the report maximized on the screen.

![image](https://user-images.githubusercontent.com/6719052/107803061-1c902a80-6d30-11eb-9caf-72a323e07a9b.png)

**Comment by namilkimfree** [comment]
In my opinion, the pass/fail icon is behind the node div, so it seems to happen when dealing with line breaks.

**Comment by namilkimfree** [comment]
https://github.com/namilkimfree/extentreports-csharp  fork version fixed issue.

**Comment by namilkimfree** [comment]
![image](https://user-images.githubusercontent.com/44854923/109527116-a4c74b80-7af6-11eb-8bbf-62eb5aacd20a.png)
