### ISSUE TITLE
Unable to perform report configuration. The file /builds/qe_automation/leawood-projects/vati/QE_Automation/extent-config.xml was not found.

### ISSUE THREAD

**Issue by utkarshsoam** [extent-framework/extentreports-csharp#126]
HI Guys while running my project in Git after 2 or 3 runs I m seeing this issue, can someone please provide me the solution to it

![image](https://user-images.githubusercontent.com/30811024/109525158-4343b480-7ad7-11eb-8341-b45ce5f21050.png)

**Comment by anshooarora** [comment]
@utkarshsoam  Looks like you have raised this issue in ExtentReports's .NET repo.  And..  this is just a warning which should not stop your tests,  but it also means the configuration file you are trying to load wasn't found.
