### ISSUE TITLE
Build failures with extent klov reporting

### ISSUE THREAD

**Issue by MaheshGooner** [extent-framework/extentreports-csharp#127]
![image](https://user-images.githubusercontent.com/18375888/110360212-55bd7100-8036-11eb-8c25-26f12bbd2602.png)

get the following errrors while i am trying  to build the project with klov package https://www.nuget.org/packages/klov-reporter/5.0.0-alpha5

**Comment by MaheshGooner** [comment]
Btw i am on .net core 3.1. would that have something to do with this issue?

**Comment by anshooarora** [comment]
Fixed in alpha-6.

**Comment by aktoluna** [comment]
Still going on. Do you have a chance to fix it?
