### ISSUE TITLE
Klov reporter build still fails on 5.0.0-alpha6

### ISSUE THREAD

**Issue by MaheshGooner** [extent-framework/extentreports-csharp#128]
Looks like https://github.com/extent-framework/extentreports-csharp/issues/127 was not fixed in the new alpha version. I still see the build errors in klov-reporter-5.0.0-alpha6

![image](https://user-images.githubusercontent.com/18375888/110452713-56e5b100-80bd-11eb-9794-713e7a31d74c.png)

![image](https://user-images.githubusercontent.com/18375888/110452762-62d17300-80bd-11eb-8e6b-ed563e218e9d.png)

**Comment by anshooarora** [comment]
Hmm.  I am not sure how these get added as they show up in Visual Studio for me after I restart, but never in my Finder.

<img width="588" alt="Screen Shot 2021-03-09 at 2 56 02 PM" src="https://user-images.githubusercontent.com/4107384/110549873-932e0700-80e7-11eb-90df-5d917a2728be.png">

Looks similar:  https://developer.mongodb.com/community/forums/t/nuget-and-snappy-libraries-impact-on-vcs-git/10011

**Comment by MaheshGooner** [comment]
@anshooarora any luck with this issue?

**Comment by samchughtai** [comment]
I am getting the same error. I hope it is not related to .Net Core 3.1

**Comment by venkivb4u** [comment]
We are getting this error with the latest alpha version. Any tentative plan to fix this?

**Comment by MaheshGooner** [comment]
@anshooarora you still plan to support this repo?

**Comment by anshooarora** [comment]
@MaheshGooner yes, version 5 is now available from the `develop` branch: https://github.com/extent-framework/extentreports-csharp/tree/develop

**Comment by MaheshGooner** [comment]
@anshooarora is a paid version available for klov? if yes what's the best way to contact?
