### ISSUE TITLE
ExtentReports 4.1.0 Not Displaying Passed %

### ISSUE THREAD

**Issue by EBH2001** [extent-framework/extentreports-csharp#137]
Good Morning,

I run my selenium tests in a .NET Core project using Extent Reports 4.1.0 and my reports are generating successfully. However, the "Passed %" does not display if I have failed tests. It only displays if all the tests pass.

Any suggestions?

Thanks!
![NoPassingTests](https://user-images.githubusercontent.com/16134915/127735929-35f7adee-2dfd-43db-89ce-5284a36d01e2.JPG)

**Comment by anaskhan5023** [comment]
@anshooarora  can you please update us on this bug ?

**Comment by moonvi** [comment]
same in ExtentReports v5.0.0-alpha6

**Comment by EBH2001** [comment]
And fast forward a year later, is there ANYONE looking into the above issue?  If not, can you suggest another report that will give the percentage correctly.

**Comment by chaituprince** [comment]
Using Extent Reports 5.0.0 in the year 2023. The issue seems to be still unresolved. The pass percentage is not showing correct numbers in any of the tables in the dashboard.

**Comment by chaituprince** [comment]
Thanks a lot @anshooarora :)
