### ISSUE TITLE
Upgrade to Chrome/Edge version 109 (ExtentReports.Core 1.0.3) - "configureView is not defined" 

### ISSUE THREAD

**Issue by DimoYa** [extent-framework/extentreports-csharp#163]
Steps to reproduced:

* Upgrade Chrome/Edge to version 109
* ExtentReports.Core 1.0.3
* ExtentV3HtmlReporter 

Generate html report file and open it with Edge/Chrome having version 109.

The user is not able to load test details:

![image](https://user-images.githubusercontent.com/25158666/212647189-46476e7a-d3d5-4b10-824b-b1f59e56c01a.png)

![image](https://user-images.githubusercontent.com/25158666/212647483-bd3e57ed-4425-4906-a34f-3e35814f886b.png)

**Comment by mava01** [comment]
Having exact same issue. Deleting that line of code does not fix the problem.

**Comment by mava01** [comment]
One of my team members found a fix for it - 
When changing links shown in picture with these
![extent-report-fix](https://user-images.githubusercontent.com/69890477/213404925-c1ed0f17-a423-4f19-a50b-ba935137d7ff.png)

`https://www.extentreports.com/resx/v3html/js/extent.js
https://www.extentreports.com/resx/v3html/css/extent.css`

Then it should fix the issue. Even changing just extent.css link fixes it.

**Comment by DimoYa** [comment]
This workaround works. Thank you

**Comment by anshooarora** [comment]
Closing - this library is not part of the framework and is maintained by SimplyTest https://www.nuget.org/packages/ExtentReports.Core.
