### ISSUE TITLE
Html log overwrites existing tests

### ISSUE THREAD

**Issue by alexp1980** [extent-framework/extentreports-csharp#17]
Hi,

I am trying to use the V3 Html logs and noticed that if I run a test say 3 times in a row, only the latest test shows in the logs. I would like the logs to show all three as they did in version 2. Is there a way to do this in the latest version or is it not ready yet?

Regards

**Comment by anshooarora** [comment]
This generally happens when you create the instance before each test. It is recommended to use a single ExtentReports instance throughout your run session.

Please share your Extent related code.

**Comment by alexp1980** [comment]
Hi,

Just to clarify I'm not running parallel tests here, just running the same test 3 times on separate occasions (which worked in version 2), code in version 4 is...

`public static ExtentReports _instance { get; } = new ExtentReports();
        public static ExtentReports Instance
        {
            get
            {
                return _instance;
            }
        }`

...and then in the OneTimeSetup...

`var logger = new ExtentV3HtmlReporter(@"c:\temp\somefilename.html");
Extent = Instance;
Extent.AttachReporter(logger);`

**Comment by anshooarora** [comment]
Version 3 onwards - there is no way to append to an existing report. This feature was removed as it was not properly built. It will be available in the future, however, I am not sure when as there are other features higher on the priority list.

**Comment by alexp1980** [comment]
Okay thanks for the info. I will stick to 2.4 for now

Regards
