### ISSUE TITLE
What is the Latest version of Extent Reporting for C# - Selenium - Specflow? I am using version 5.0.0-alpha6 and have issue

### ISSUE THREAD

**Issue by shubautomation** [extent-framework/extentreports-csharp#175]
Hi @anshooarora ,

I am using extent reporting version 5.0.0-alpha6 for C#, selenium and Specflow combination.

I have observed that sometime Steps for Pass scenario did not get expand once clicked on the Pass scenario in Report. Please see below screenshot
![image](https://github.com/extent-framework/extentreports-csharp/assets/115528914/bb99ef4d-5ea5-47dc-9985-224392a15f84)

In this above screenshot, Pass scenario has three-four steps which are passed but in report it is not getting displayed even when I clicked on the pass scenario. Ideally when clicking on the pass/fail scenario, it should get expand and steps should display but it is not happening. 

Need your help to resolev this issue ASAP.

Note: It is not happening for all the scenarios.

**Comment by anshooarora** [comment]
The first beta was released yesterday: https://www.nuget.org/packages/ExtentReports/5.0.0-beta1

There are several changes and fixes available. Please check and revert back if you continue to face this issue.

**Comment by shubautomation** [comment]
> ~The first beta was released yesterday: https://www.nuget.org/packages/ExtentReports/5.0.0-beta1~
> 
> Refer https://www.nuget.org/packages/ExtentReports#versions-body-tab for the latest available version.
> 
> There are several changes and fixes available. Please check and revert back if you continue to face this issue.

Hi @anshooarora ,

I upgrade to Extent reporting to 5.0.0-beta1but still facing the same issue. Could you please rectify it please.

**Comment by anshooarora** [comment]
Please share a sample report file with the behavior you've described.

**Comment by shubautomation** [comment]
> Please share a sample report file with the behavior you've described.

Hi @anshooarora ,

I cant share the report(due to complaince) as it is my official project report. And to reproduce this issue I might need to have lots of sample TCs ( this will be little challenging for me to generate the Sample report)

Any other way I can help to make issue reproducible?

**Comment by anshooarora** [comment]
Closing since there was no response from OP.  Feel free to open a new ticket if you're still facing this issue.
