### ISSUE TITLE
MongoDB driver vulnerability

### ISSUE THREAD

**Issue by pharrap** [extent-framework/extentreports-csharp#185]
The version of MongoDB driver in the project is outdated and triggering vulnerability reports in Snyk.
https://security.snyk.io/vuln/SNYK-DOTNET-MONGODBDRIVER-3329316

I see a friendly bot has already auto-generated a pull request to bump the version but it hasn't been merged yet:
https://github.com/extent-framework/extentreports-csharp/pull/168

**Comment by anshooarora** [comment]
#168 can no longer be merged since 4.x was moved to its own branch with the release of 5.0.0.  I have bumped versions for all vulnerabilities and will try to publish the latest 4.x package soon.

**Comment by Divya-git23** [comment]
Hi
I see extentreports-csharp is updated to fix all those vulnerabilities 
https://github.com/extent-framework/extentreports-csharp/releases

But ExtentReports.Core is still having 1.0.3 as latest and which is having Mongodb.driver version 2.0.8 
The version of MongoDB driver in the project is outdated and triggering vulnerability reports in Snyk.
https://security.snyk.io/vuln/SNYK-DOTNET-MONGODBDRIVER-3329316

Any plans to update this ExtentReports.Core Mongodb.driver version ASAP
