### ISSUE TITLE
Image not being created in screenshot?

### ISSUE THREAD

**Issue by Fergal-C** [extent-framework/extentreports-csharp#190]
Windows
NET version 7.0.10
Extent Reports 5.0.0

I am using the following code to generate a screenshot for a failed test, but no image is actually being created in the test report:

`test.Fail("Screenshot", MediaEntityBuilder.CreateScreenCaptureFromPath("." + @"/extent.png").Build());`

![Screenshot](https://github.com/extent-framework/extentreports-csharp/assets/20088633/ec34095d-9f1e-4623-9b14-486707989e8c)

The file path, from the broken image, appears correct "Reports/2023/12Sep/extent.png", where the report is stored in "Reports/2023/12Sep/"

Is there a known reason why the screenshot image is not created?

(Apologies if this is not an appropriate place for this question.)

**Comment by anshooarora** [comment]
Can you check the HTML on the report for the image path using devtools? Try using "extent.png" directly?

**Comment by Fergal-C** [comment]
Thanks anshooarora,

This is the image html from the report in dev tools:
`<img data-featherlight="./extent.png" src="./extent.png">`

When the code is changed to:
`test.Fail("Screenshot", MediaEntityBuilder.CreateScreenCaptureFromPath("extent.png").Build());`

The img html from the report in DevTools changes to
`<img data-featherlight="extent.png" src="extent.png">`

But the image still does not load.
![Screenshot2](https://github.com/extent-framework/extentreports-csharp/assets/20088633/6b4f6758-bbf4-4604-86d2-dca9c100bb68)

I also can't find the image locally, when I search for it in File Explorer, it seems like it is not being created.

**Comment by Fergal-C** [comment]
Thanks very much again anshooarora, that's exactly what I was misunderstanding. All working now.
