### ISSUE TITLE
Time Taken Badge on Report Says "secs" instead of "ms"

### ISSUE THREAD

**Issue by bryanh-bloomerang** [extent-framework/extentreports-csharp#194]
[](url)I've recently started using extent reports and noticed that the time taken badge on a tests is showing "secs". I believe it should say "ms". Given the screenshot below, the start time of this particular test is at 12:39:38 PM and the end time is 12:39:43 PM. The time badge says "5119.81 secs". Given the start and end time and know how long this test generally takes, the value provided is in milliseconds not seconds, so the label should be "ms".

<img width="967" alt="Screenshot 2023-10-17 at 1 41 52 PM" src="https://github.com/extent-framework/extentreports-csharp/assets/129969421/126c97b1-fab6-40f6-a6a7-63b30c83e300">

**Comment by sudheshg** [comment]
@bryanh-bloomerang  PR has been raised. [](url) https://github.com/extent-framework/extentreports-csharp/pull/195

**Comment by joegardiner** [comment]
It would be good if this would display as ms if below 1s, and seconds above 1s

**Comment by anshooarora** [comment]
Closing since PR is now merged.

For the feature request toggling between ms/s, please see https://github.com/extent-framework/extentreports-csharp/issues/204
