### ISSUE TITLE
Tables in the graphs section not calculating percentages for BDD tests

### ISSUE THREAD

**Issue by emerson-b** [extent-framework/extentreports-csharp#198]
When tagging BDD tests with Author / Tags, the tables generated do not show the correct passed percentage, instead showing 0%
![image](https://github.com/extent-framework/extentreports-csharp/assets/5680833/8ee30e86-271d-45db-a372-cfef318d9903)

**Comment by anshooarora** [comment]
Closing as this was fixed in #137 and will be part of 5.0.2.
