### ISSUE TITLE
After upgrading to v4.0 2 html files are produced and they don't display correctly

### ISSUE THREAD

**Issue by paulmccormack** [extent-framework/extentreports-csharp#20]
I upgraded to v4.0.0.  I haven't made any changes to how I initialise the report but now 2 html files are produced.  One is called index and the other dashboard.  Neither display correctly like the old report.

**Comment by anshooarora** [comment]
The default version 4 reporter produces 4 files in total: 2 of them you've mentioned and the other 2 are conditional upon tags/exceptions.  

Can you tell me what is not being displayed correctly?

PS. To use the version 3 reporter, you can initialize `ExtentV3HtmlReporter`.

**Comment by paulmccormack** [comment]
<img width="768" alt="extent" src="https://user-images.githubusercontent.com/12688439/50950488-3bdb7e80-14fe-11e9-87f7-ea04746777be.png">

**Comment by paulmccormack** [comment]
If i change the size of the window the report will not scale.  You just lose the test steps sections

**Comment by anshooarora** [comment]
So one of the issues only smaller displays, or when you resize the browser to about 1340px wide. A simple media query would fix it.

The other issue is the test-name going over the date when resized, also a css fix.
