### ISSUE TITLE
Race condition in MediaEntityBuilder

### ISSUE THREAD

**Issue by arnonax-tr** [extent-framework/extentreports-csharp#201]
I encountered a potential race condition in `MediaEntityBuilder`. I submitted a PR to fix it: #200 to fix it.

Note: I encounter an occasional issue with empty screenshots, which may be caused or related to that fix, but I still can't prove it. I encountered this potential bug when searching for the root cause of my issue.

**Comment by anshooarora** [comment]
@arnonax-tr Thanks for the PR, it can indeed cause subtle issues, merged.  Closing this issue.
