### ISSUE TITLE
CSharp: Merge multiple Spark reports

### ISSUE THREAD

**Issue by saravanakumar-nc** [extent-framework/extentreports-csharp#214]
Hi,
I noticed a thread, but for Java where there is a way to merge multiple Spark reports into one html report.
Is there a way to Merge the Spark html reports generated in CSharp?

In Java, looks like they are using Json file to merge the reports.
Java ref. thread - https://github.com/extent-framework/extentreports-java/issues/331

**Comment by PatrickLeGarrec** [comment]
Same here. in  C# extent.attachReporter take 1 arg only, not 2.
merging does not seem to be implemented in 5.0.2, or i miss something...

**Comment by anshooarora** [comment]
Can you try with this?

https://extentreports.com/docs/versions/5/net/index.html

A little bit more context here:  https://github.com/extent-framework/extentreports-java/issues/184

**Comment by PatrickLeGarrec** [comment]
![extent](https://github.com/extent-framework/extentreports-csharp/assets/89050431/a545e5d0-b066-49e6-83e7-d631b1bcd195)

AttachReporter take 1 argument .  
extent.AttachReporter(json, spark);   => not available

**Comment by anshooarora** [comment]
Call this method twice, for each reporter?

**Comment by PatrickLeGarrec** [comment]
oh maybe i m wrong. will try to call this twice. 
I just start to experiment the merging capabilities. i will try next week.

Great library.
thank you for your quick support.

**Comment by anshooarora** [comment]
See here:  https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Core/ExtentReports.cs#L144.  The method is available.  What version are you using?

**Comment by Saravana-Kumar-N-ZS0542** [comment]
My bad, its there. It works absolutely fine. 

This is how I have implemented incase if any one needed it.

// Ensure your existing test suites are configured to generate both JSON and HTML reports
var extent = new ExtentReports();
var htmlReporter = new ExtentHtmlReporter("extent-report.html");
var jsonReporter = new ExtentJsonReporter("extent-report.json");
extent.AttachReporter(jsonReporter, htmlReporter);

// Run your tests and log the results

// Finally make sure to flush it
extent.Flush();

Once we have all the test results, we can generate the merged report.
Lets say we have 3 test results at "testresults" directory as below...
TestSuite1 - this will have extent-report.html, extent-report.json
TestSuite2 - this will have extent-report.html, extent-report.json
TestSuite3 - this will have extent-report.html, extent-report.json

string outputDirectory = "\\testresults";
string[] jsonFiles = Directory.GetFiles(outputDirectory, "*.json", SearchOption.AllDirectories);

var extent = new ExtentReports();

foreach (var jsonFile in jsonFiles)
{
    extent.CreateDomainFromJsonArchive(jsonFile);
}

var mergeSparkReporter = new ExtentSparkReporter(outputDirectory + @"\Final\merged-extent-report.html");
mergeSparkReporter.LoadJSONConfig("spark-config.json"); // if you have any config file

extent.AttachReporter(mergeSparkReporter);
extent.Flush();

Thanks for your help. We shall close this.

**Comment by saravanakumar-nc** [comment]
My bad, its there. It works absolutely fine.

This is how I have implemented incase if any one needed it.

// Ensure your existing test suites are configured to generate both JSON and HTML reports
var extent = new ExtentReports();
var htmlReporter = new ExtentHtmlReporter("extent-report.html");
var jsonReporter = new ExtentJsonReporter("extent-report.json");
extent.AttachReporter(jsonReporter, htmlReporter);

// Run your tests and log the results

// Finally make sure to flush it
extent.Flush();

Once we have all the test results, we can generate the merged report.
Lets say we have 3 test results at "testresults" directory as below...
TestSuite1 - this will have extent-report.html, extent-report.json
TestSuite2 - this will have extent-report.html, extent-report.json
TestSuite3 - this will have extent-report.html, extent-report.json

string outputDirectory = "\testresults";
string[] jsonFiles = Directory.GetFiles(outputDirectory, "*.json", SearchOption.AllDirectories);

var extent = new ExtentReports();

foreach (var jsonFile in jsonFiles)
{
extent.CreateDomainFromJsonArchive(jsonFile);
}

var mergeSparkReporter = new ExtentSparkReporter(outputDirectory + @"\Final\merged-extent-report.html");
mergeSparkReporter.LoadJSONConfig("spark-config.json"); // if you have any config file

extent.AttachReporter(mergeSparkReporter);
extent.Flush();

Thank you for your help. I am closing this.
