### ISSUE TITLE
Report not properly loading

### ISSUE THREAD

**Issue by emerson-b** [extent-framework/extentreports-csharp#216]
Hi, I've been using extent for the past year across 3 different reports in a pipeline.

The past few weeks, one of the reports has stopped generating properly and loads the html incorrectly. The data in the main report doesn't properly format and all of the side categories show as empty.

Attached is a video of the working report, followed by the broken report (can't upload the html files) 

https://github.com/extent-framework/extentreports-csharp/assets/5680833/dcf7fda2-ae10-4ef8-9e59-76a9e4a68bef

Any advice on how to fix the report would be fantastic. 

Thanks

**Comment by anshooarora** [comment]
Would it be possible to share the report with me? I am suspecting an unclosed HTML tag which may be breaking this layout. Anything with `<` or `>` remaining unclosed.

**Comment by emerson-b** [comment]
Sure, here's a link, https://drive.google.com/file/d/1JxopmLULXMbTB37gs-UrZNPJHg-Hvcri/view?usp=drivesdk

**Comment by anshooarora** [comment]
Hmm, this is a bug.

RawGit has been deprecated and this is occurring because jsontree.js isn't accessible. I will change the endpoint to jsdelivr and push new release.

**Comment by anshooarora** [comment]
Reference:  https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Views/Spark/Partials/Head.cshtml#L25

Can you run with OfflineMode config?

**Comment by anshooarora** [comment]
Above fix is now merged.  Working on releasing the latest to nuget.

**Comment by anshooarora** [comment]
You can now use: https://www.nuget.org/packages/ExtentReports/5.0.4

**Comment by emerson-b** [comment]
Hi @anshooarora, this latest version is still causing the above issue to happen. Is there anything else I should look for?

**Comment by emerson-b** [comment]
I've attached a copy of the report using version 5.0.4
https://drive.google.com/file/d/1fPyHj5xbDx46QMonZpaiWFnSlykELf06/view?usp=sharing

**Comment by emerson-b** [comment]
Thanks for the info, I'll give that a go!
