### ISSUE TITLE
Duration formatting

### ISSUE THREAD

**Issue by jrod567** [extent-framework/extentreports-csharp#218]
In v4, the duration of test was automatically formatted to hours/min/seconds/ms.  In v5, it appears to always be in ms.

Is it possible to format the duration of a test?

For example:

![image](https://github.com/extent-framework/extentreports-csharp/assets/48925899/542f0d9b-b3a3-4d61-86c7-f41b74cb1373)

**Comment by anshooarora** [comment]
Agreed.  Version 4 impl was better IMO:

```
<p class="duration text-sm">@test.RunDuration.ToString("''h'h:'m'm:'s's+'fff'ms'")</p> 
<span class="datetime">@test.StartTime.ToString("HH:mm:ss tt")</span>
```

Impacted line of code:  https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Views/Spark/Partials/SparkTestSPA.cshtml#L78

**Comment by anshooarora** [comment]
Closing this as the above PR reverts to the old way of showing a test's run duration:

![image](https://github.com/extent-framework/extentreports-csharp/assets/4107384/7fdf6827-bd47-4a25-9640-08e78d368e55)
