### ISSUE TITLE
v4.0 Logger Report, Navbar contains incorrect references to other html files

### ISSUE THREAD

**Issue by shack05** [extent-framework/extentreports-csharp#22]
Each file produced by the logger reporter has `logger` at the start of the file name (eg `loggerDashboard.html`) whilst the links in the navigation bar don't (eg `dashboard.html`). As such, navigating to the other views via the navigation bar doesn't work.

**Comment by anshooarora** [comment]
@shack05 

Can you share your initializing code?  Note: all version 4 reporters require a directory input instead of file. From [docs](http://extentreports.com/docs/versions/4/net/logger-reporter.html)

```
// directory where output is to be printed
var logger = new ExtentLoggerReporter("user/build/name/");
```

**Comment by shack05** [comment]
@anshooarora 

I've realised it was an error on my end by not providing the trailing slash on the path.

So if I provide this input:
`var loggerReporter = new ExtentLoggerReporter(Path.Combine(TestContext.CurrentContext.TestDirectory, "Logs/logger"));`

it will create the html files in the 'Logs' and prepend the word 'logger' to each filename, there navigation doesn't work.

If I provide the trailing slash, i.e:
`var loggerReporter = new ExtentLoggerReporter(Path.Combine(TestContext.CurrentContext.TestDirectory, "Logs/logger/"));`

it puts the files in the 'logger' directory and they do not have 'logger' at the start.
