### ISSUE TITLE
Duplicate graph in Dashboard when Analysis.Strategy = Test

### ISSUE THREAD

**Issue by jrod567** [extent-framework/extentreports-csharp#220]
In v5, I've noticed a duplicate graph of the "Tests" graph when ExtentReports.Report.AnalysisStrategy = AnalysisStrategy.Test.  This was not the case in v4:

![image](https://github.com/extent-framework/extentreports-csharp/assets/48925899/04603e53-d651-4cd4-a6f6-ebb27b247678)

**Comment by jrod567** [comment]
Looking at the dashboard closer, it also appears the total run duration is missing/no longer available as seen in v4.  A different issue , but wanted to make mention of it.

**Comment by anshooarora** [comment]
This is a bug.  I'm able to reproduce this with the following:

```cs
using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;

var extent = new ExtentReports();
extent.AttachReporter(new ExtentSparkReporter("index.html"));
extent.CreateTest("Test").CreateNode("Node").CreateNode("Node").Pass();
extent.Flush();
```

**Comment by anshooarora** [comment]
> Looking at the dashboard closer, it also appears the total run duration is missing/no longer available as seen in v4. A different issue , but wanted to make mention of it.

This would be an enhancement.  Can you open a new issue for this?  Thanks.

**Comment by anshooarora** [comment]
Also published a new package with the fixes:  https://www.nuget.org/packages/ExtentReports/5.0.5-beta1

**Comment by jrod567** [comment]
Thank you anshooarora!   Confirmed working in 5.0.5-beta1

**Comment by jrod567** [comment]
> > Looking at the dashboard closer, it also appears the total run duration is missing/no longer available as seen in v4. A different issue , but wanted to make mention of it.
> 
> This would be an enhancement. Can you open a new issue for this? Thanks.

Created [https://github.com/extent-framework/extentreports-csharp/issues/222](url)
