### ISSUE TITLE
Inserting HTML

### ISSUE THREAD

**Issue by CMALD** [extent-framework/extentreports-csharp#25]
I read the documentation from 

       https://github.com/extent-framework/extentreports-csharp/issues/new

and when I copy the code example, I got syntax errors:

            extent.Log(LogStatus.Info , "HTML" , "Usage: <b>BOLD TEXT</b>");

In ExtentReports class I didn't found fanction  Log(), 
Additional, what is LogStatus class? maybe it refer to Status enum?

**Comment by anshooarora** [comment]
Docs need correction, it is the Status enum indeed.

**Comment by anshooarora** [comment]
Issue has been fixed.

**Comment by CMALD** [comment]
There are 2 additional fixes to the above example:

         extent.Log(Status.Info, "HTML", "Usage: <b>BOLD TEXT</b>");
 
1. test.Log instead of extent.Log
2. According to the example, it seems that the method Log get 2 strings; 
the first is "HTML" and the second is "Usage:< b> BOLD TEXT < / b>"
but actually, it get one string only.

**Comment by anshooarora** [comment]
Also updated, thank you for your help!
