### ISSUE TITLE
Double screenshot in logs

### ISSUE THREAD

**Issue by pavlikpatrycja** [extent-framework/extentreports-csharp#26]
Hello, 
I'm using 3.1.1 version due to problems with ExtentHtmlReporter configuration in 3.1.3. When I'm adding screenshot to logs by extTest.Fail(htmlStr, MediaEntityBuilder.CreateScreenCaptureFromPath("name.png").Build()); it is doubled in html report. Is it a bug or am I doing something wrong? Thanks in advance. 
![2019-01-15_10h35_30](https://user-images.githubusercontent.com/14920046/51171539-7b64ea80-18b1-11e9-93dd-0e863ba7ed0b.png)

**Comment by anshooarora** [comment]
Can you please check with the latest csharp version 4.0.1 and report back?

**Comment by pavlikpatrycja** [comment]
In 4.0.1 version configuration of ExtentHtmlReporter is fine and attached screenshots are not doubled but size of screenshot is very big. Can I customize the size of screenshots?

**Comment by anshooarora** [comment]
This will become standard starting 4.0.2, but for now you can use the below config:

```
img.r-img { width: 5%; max-width: 5%; }
```
