### ISSUE TITLE
V4.0.1 reports some issues

### ISSUE THREAD

**Issue by CMALD** [extent-framework/extentreports-csharp#27]
-------  index.html file:
1.1. description of CreateNode method doen not diaplayed in report
          (This issue refer to ExtentHtmlReporter  report type)
 
-------   tag.html file:
2.1. TestName value in main table does not appears as link (as ExtentV3HtmlReporter type)
(This issue refer to ExtentLoggerReporter & ExtentHtmlReporter  report types)

2.2.  List of tags appears as non spaces between words 
example:

       test.AssignCategory("Tag Name");
appears as "TagName" 
(as one word)
(This issue refer to all report types)

**Comment by anshooarora** [comment]
1.1 Fixed

2.1 Do you mean with the `cursor:pointer`?  

2.2 This is expected as having spaces breaks search/filters.

**Comment by CMALD** [comment]
html reporter:
![htmlreport](https://user-images.githubusercontent.com/46340089/51302436-0b826b80-1a3b-11e9-813b-556e18d72ab8.png)

html v3 reporter:
![htmlv3report](https://user-images.githubusercontent.com/46340089/51302555-6ae07b80-1a3b-11e9-8faf-54af10fd3cb3.png)

I mean that the test name will be clickable, and will moving to the linked test steps in index page

**Comment by CMALD** [comment]
Description of **CreateTest** method does not displayed in report
(This issue refer to **ExtentV3HtmlReporter** report type)
