### ISSUE TITLE
report.Config.Theme = Theme.Dark Issue

### ISSUE THREAD

**Issue by CMALD** [extent-framework/extentreports-csharp#29]
ExtentV3HtmlReporter type:
when opening the .html report file, the default display is standard, even though I defined report theme to dark.
(Only after clicking on the bottom left icon on the screen, the dark theme is displayed)

ExtentLoggerReporter type:
index.html file
dark theme does not displays even though I define report theme to dark.
(tag.html and index.html files displays OK dark theme)

ExtentHtmlReporter:
The bottom left icon that should replace between dark and standard themes not exists)

Enhancement:
Why would not there be a global option for any type of report to switch from dark to standard (by bottom left icon) even if I do not specify in the code Theme.Dark?

**Comment by anshooarora** [comment]
Global configuration options are not possible via Extent because:

* it acts as an Observable
* not all reporters support this option
* what Reporters do/show should independent of the API

PS.  `ExtentHtmlReporter` and `ExtentLoggerReporter` can switch theme using the "L" key.
