### ISSUE TITLE
Change "path" argument to getting special chars

### ISSUE THREAD

**Issue by CMALD** [extent-framework/extentreports-csharp#31]
Hello,

I try run this:

    testAction.Log(Status.Info , "Click On", MediaEntityBuilder.CreateScreenCaptureFromPath(@"E:2. Click on 'loginButton'.Jpeg").Build());

But the screenshot image didn't attached  to the report, 

Only when I change the image name to: "2 Click on loginButton.Jpeg" and respectively the code to: 
          
    testAction.Log(Status.Info , "Click On", MediaEntityBuilder.CreateScreenCaptureFromPath(@"E:\2 Click on loginButton.Jpeg").Build());

without special chars; **point** and **apostrophe**, only then the report attaches  the screenshot file.

Is it possible to add support in special chars for path string arguments?

This issue relevant to below functions
1. CreateScreenCaptureFromPath, CreateScreenCaptureFromPath 
2. Constructors of all report types

**Comment by anshooarora** [comment]
This is not possible as the browser will not show the image.  Extent cannot control what happens after it sets the path, its up to the browser to show it.
