### ISSUE TITLE
Environment collection update missing in ExtentKlovReporter

### ISSUE THREAD

**Issue by ashwin-ak** [extent-framework/extentreports-csharp#38]
Environment collection update missing in ExtentKlovReporter. The fix which I had posted for version 3.

https://github.com/anshooarora/extentreports-csharp/pull/131

following method call.

`InsertUpdateSystemAttribute();`

below method.

`private void InsertUpdateSystemAttribute()
        {
            List<SystemAttribute> systemAttrList = _reportAggregates.SystemAttributeContext.SystemAttributeCollection;

            foreach (SystemAttribute sysAttr in systemAttrList)
            {
                var document = new BsonDocument
                {
                    { "project", ProjectId },
                    { "report", ReportId },
                    { "name", sysAttr.Name }
                };

                BsonDocument envSingle = _environmentCollection.Find(document).FirstOrDefault();

                if (envSingle == null)
                {
                    document.Add("value", sysAttr.Value);
                    _environmentCollection.InsertOne(document);
                }
                else
                {
                    ObjectId id = envSingle["_id"].AsObjectId;

                    document = new BsonDocument
                    {
                        { "_id", id },
                        { "value", sysAttr.Value }
                    };

                    _environmentCollection.UpdateOne(
                            new BsonDocument("_id", id),
                            new BsonDocument("$set", document));
                }
            }
        }`

**Comment by anshooarora** [comment]
Thank you again.  Can you send a pull request?
