### ISSUE TITLE
When using ExtentTest.AddScreenCaptureFromBase64String with title, the title isn't being passed to the html although it has value

### ISSUE THREAD

**Issue by WarleyLopes** [extent-framework/extentreports-csharp#39]
I believe this should be tagged as an improvement request.

When adding an image in Base64String through an ExtentTest object:

e.g.:
`this._ExtentTest.AddScreenCaptureFromBase64String(imageIntoBase64,"sampleTitle");`

In ExtentTest class, when using AddScreenCaptureFromBase64String, the ScreenCapture object is [built](https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/ExtentTest.cs#L547) with both base64String and title values but when building the html, it's value isn't used per what we can see [here](https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Views/Html/Partials/SparkStandard.cshtml#L21).

Also consider when the ScreenCapture is built through MediaEntityBuilder instead, its object is being created with default in-code fixed value of null as per what we can see [here ](https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/MediaEntityBuilder.cs#L43), so, I guess this also should be changed to include the use of @sc.Name when building the html.

**Comment by anshooarora** [comment]
This was recently fixed in the Java implementation too.  The title will appear as the `alt` or `title` or `content` property and will be displayed when you hover mouse over the image.

**Comment by WarleyLopes** [comment]
Thanks a lot for your response Anshoo, I'll be waiting for this fix then!!

Why can't it be simply the inner text of the span with the CSS class "file-name"?

I took a look at the java implementation as you said and indeed it builds the ScreenCapture object passing the value for the title when using base64String but I couldn't find how the html was built using the value in Java, but, no problem!

**Comment by anshooarora** [comment]
> Why can't it be simply the inner text of the span with the CSS class "file-name"?

Because the `title` attribute is generally used to provide additional information about an element, generally via a mouseover..   Once the markup is created, you can run execute post-processing js to add the title attribute to the innerHtml like so (untested):

```
$("img").filter(function() {
    return $(this).attr("title") !== "";
}).each(function() {
    var t = $(this);
    t.text(t.text() + t.attr("title"));
});
```

**Comment by TJEvans** [comment]
This is the same for MediaEntityBuilder.CreateScreenCaptureFromBase64String, when declaring a title it is never used.  I tried to create a pull request that passed the title on to the ScreenCapture constructor and modify the ScreenCapture Source/SourceIcon string fields to utilize title in place of "base64-img" when it is not null or empty but got a 403.

**Comment by anshooarora** [comment]
Title is now available in both Html/V3Html reporters as a mouseover title.
