### ISSUE TITLE
Unable to remove Extent logo from the report(ExtentV3HtmlReporter)

### ISSUE THREAD

**Issue by sharonangeladara** [extent-framework/extentreports-csharp#41]
The report generated does not reflect any of the custom javascript added to the extent-config file.

**Comment by foursyth** [comment]
Customization are generally user-specific, out of the product's scope and due to time-constraints, we are unable to work on these.  I would highly suggest opening a ticket on Stackoverflow or using CSS/JS to disable or hide this element.

**Comment by foursyth** [comment]
@anshooarora please close
