### ISSUE TITLE
Documentation issue: change "Java" text in .NET code examples to ".NET"

### ISSUE THREAD

**Issue by CMALD** [extent-framework/extentreports-csharp#46]
go to: [http://extentreports.com/docs/versions/4/net/](url)
The text "java" on the upper right of the code snippets should be ".NET"?!

![Java_Text](https://user-images.githubusercontent.com/46340089/54269200-98522d00-4585-11e9-84dd-ae2cce180730.png)

**Comment by anshooarora** [comment]
Issues fixed.
