### ISSUE TITLE
AppendExisting is not available anymore on ExtentHtmlReporter

### ISSUE THREAD

**Issue by lionelberton** [extent-framework/extentreports-csharp#50]
AppendExisting is not available anymore in v4 and nothing is indicated in the breaking changes, nor how to migrate from v3 to v4.
Could you please give some indications?

**Comment by foursyth** [comment]
As far as I know, this feature was never implemented in v3.  This is an open issue in the Java repo as well, and you will notice it is marked as slow-burner because of the complexity and level of effort required. 

@anshooarora  this can be marked an enhancement for a future release.

**Comment by alexp1980** [comment]
Hello. Any update on whether this will be implemented any time soon? Thanks.

**Comment by CandyButcherZA** [comment]
Hi @anshooarora. We are looking to append test results into one HTML file using C# v4. Is this going to be implemented anytime soon?

**Comment by anshooarora** [comment]
This will be implemented but not in version 4.  This feature requires quite a bit of re-engineering as version 4 has a ton of reporters, each with own nuances.  Working on the version 5 which will include this feature..  no ETA as of now though.

**Comment by anshooarora** [comment]
This was recently added in the Java binding and will soon be available in the .NET implementation.

**Comment by AutomationSifu** [comment]
Hi @anshooarora !  I hope all is well.  I just wanted to check in and see if this functionality has been added to the latest .Net version or possibly the estimate time range to fix.  I downloaded version 4.0.3 for the .net bindings but I don't see the AppendExisting method or unless it's called something else.  Thanks in advance for your help.

**Comment by AutomationSifu** [comment]
Hi @anshooarora !  I just wanted to check in on this item to see if there is an update?

**Comment by anshooarora** [comment]
Sorry for the delay.  This was recently reintroduced in Java version 5 pre-release, and will be included in the coming few weeks for .NET as well.

**Comment by sundusnisar** [comment]
Hi, Is it added to .Net?

**Comment by mahesh-thummala-fluke** [comment]
Hi @anshooarora Any Update on the v5.0, I am eagerly waiting for AppendExisting Html file

**Comment by anshooarora** [comment]
Hi, this feature is available starting version 5.  Docs here:  https://www.extentreports.com/docs/versions/5/net/index.html#combine-multiple-reports

**Comment by lijinxinKing** [comment]
Hello, is this feature available in version 5 for .NET? Where can I find the documentation? Thank you.

**Comment by lijinxinKing** [comment]
Hello, is this feature available in version 5 for .NET? Where can I find the documentation? Thank you.

**Comment by anshooarora** [comment]
@lijinxinKing This feature is available using the [JsonFormatter](https://www.extentreports.com/docs/versions/5/net/index.html#combine-multiple-reports):

```
var spark = new ExtentSparkReporter("spark.html");
var json = new ExtentJsonFormatter("extent.json");
var extent = new ExtentReports();
extent.CreateDomainFromJsonArchive("extent.json");
extent.AttachReporter(json, spark);
```
