### ISSUE TITLE
export raw data

### ISSUE THREAD

**Issue by orchohenkryon** [extent-framework/extentreports-csharp#51]
hi
is there an option to create a "raw data" report in an xml or json format in addition to the html report?
(for analytics option , throwing it to elastic search or somthing)

**Comment by foursyth** [comment]
if you use Klov, data is stored in MongoDb which you can use to create a json extract.

**Comment by coolvasanth** [comment]
Is there any other way, other than MongoDB ? for generation of CI build, I need a JSON/XML file that gives the list with passed and failed test cases.

**Comment by anshooarora** [comment]
This feature is available version 5 onwards with `ExtentJsonFormatter`.  [Here is an example](https://www.extentreports.com/docs/versions/5/net/index.html#combine-multiple-reports) of its usage shown to combine multiple reports.  But, if it is a JSON output of the entire run session you need, you won't need to call `CreateDomainFromJsonArchive`.

**Comment by coolvasanth** [comment]
@anshooarora  thanks for the reply, let me have a look at it.
