### ISSUE TITLE
Need ability to set ReportStartDateTime and ReportEndDateTime

### ISSUE THREAD

**Issue by soul4soul** [extent-framework/extentreports-csharp#52]
I ran the [extentreports-dotnet-cli](https://github.com/extent-framework/extentreports-dotnet-cli) with some nunit test results. The report uses the datetime from the time the cli app is executed and processing.

I expect the `ReportStartDateTime ` and `ReportEndDateTime` to be equal to the start-time and end-time within the nunit results file.

**Comment by foursyth** [comment]
@anshooarora can you please look into this?  This is an enhancement requred.

**Comment by anshooarora** [comment]
This can now be updated using:

```
extent.ReportStartDateTime
extent.ReportEndDateTime
```
