### ISSUE TITLE
Number of features is equal to number of scenarios

### ISSUE THREAD

**Issue by ParagRaut** [extent-framework/extentreports-csharp#54]
I have multiple Features which have multiple number of scenario in each of them.
In reports I see # of Feature is equal to # of Scenarios which I know is wrong.
Below is screenshot:
![image](https://user-images.githubusercontent.com/16030809/56348808-876d8a80-61c7-11e9-91a9-ee3aafb5d5d2.png)

I'm using BDD approach and these methods to create nodes:
`case "Given":
                        ScenarioName.CreateNode<Given>(stepName);
                        break;
                    case "When":
                        ScenarioName.CreateNode<When>(stepName);
                        break;
                    case "Then":
                        ScenarioName.CreateNode<Then>(stepName);
                        break;
                    case "And":
                        ScenarioName.CreateNode<And>(stepName);
                        break;`

Can you tell me if I'm doing something wrong ?

**Comment by rudreshtrivedi** [comment]
private static ExtentTest featureName;
        private static ExtentTest scenario;

 **[BeforeFeature]**
        public static void BeforeFeature()
        {
            featureName = extent.CreateTest<Feature>(FeatureContext.Current.FeatureInfo.Title);
        }
 **[AfterStep]**
        public void InsertReportingSteps()
        {
            try
            {
                var stepType = ScenarioStepContext.Current.StepInfo.StepDefinitionType.ToString();

                if (ScenarioContext.Current.TestError == null)
                {
                    if (stepType == "Given")
                        scenario.CreateNode<Given>(ScenarioStepContext.Current.StepInfo.Text);
                    else if (stepType == "When")
                        scenario.CreateNode<When>(ScenarioStepContext.Current.StepInfo.Text);
                    else if (stepType == "Then")
                        scenario.CreateNode<Then>(ScenarioStepContext.Current.StepInfo.Text);
                    else if (stepType == "And")
                        scenario.CreateNode<And>(ScenarioStepContext.Current.StepInfo.Text);
                }


See above example! 
are you using correct annotation and  Feature/Scenario terminology?

**Comment by ParagRaut** [comment]
@rudreshtrivedi in above example you're not initializing scenario, 
i.e. private static ExtentTest scenario;

I use following before initializing the test,

FeatureName = ExtentReports.CreateTest<Feature>(FeatureContext.Current.FeatureInfo.Title);
ScenarioName = FeatureName.CreateNode<Scenario>(ScenarioContext.Current.ScenarioInfo.Title);

One thing I noticed is I put both statement in before scenario tag, which I can correct now

**Comment by ParagRaut** [comment]
Thanks it solved my issue now I do this:
[BeforeFeature]
        protected static void InitializeCurrentFeatureContext()
        {
            if (IsExtentReportsEnabled)
            {
                ExtentReporter.InitializeCurrentFeatureContext(); 
            }
        }

[BeforeScenario]
        protected static void InitializeScenarioContext()
        {
            if (IsExtentReportsEnabled)
            {
                ExtentReporter.InitializeCurrentScenarioContext();
            }
        }

Which is basically doing both steps separately in different tags, thanks again

**Comment by rudreshtrivedi** [comment]
Welcome
