### ISSUE TITLE
New Feature Request: Override "Warning" status to "Pass" throught out report and display indication

### ISSUE THREAD

**Issue by MelWicky** [extent-framework/extentreports-csharp#56]
This is related to a prior issue I found in the java repository:

https://github.com/anshooarora/extentreports-java/issues/19

Is this same functionality possible in the C# version?  I'm setting the java script that was in this closed example but it is not updating the charts.  It is updating the status in the subview.

            HtmlReport.Configuration().JS = "$('.test.warning').each(function() { $(this).addClass('pass').removeClass('warning'); }); $('.test-status.warning').each(function() { $(this).addClass('pass').removeClass('warning').text('pass'); });$('.tests-quick-view .status.warning').each(function() { $(this).addClass('pass').removeClass('warning').text('PASS'); }); testSetChart();";

I would also like the ability to have an indicator of warning but now affect the counts and the chart.  In the old issue you provided this as the solution:

test.getTest().internalWarning = "Warning";

I am not able to translate this into anything that works.  Is this functionality available in the C# version too? If not, can it be added?

**Comment by anshooarora** [comment]
This feature is available in the Java version.  It will be possible to override the Status hierarchy by specifying your own without using a JavaScript call workaround to achieve this.

**Comment by anshooarora** [comment]
You can now set your own status hierarchy using the below method.  The hierarchy below states PASS will always be prioritized before Warning.  The original hierarchy has Warning taking precedence, source: https://github.com/extent-framework/extentreports-csharp/blob/net-core/extentreports-dotnet-core/Model/StatusHierarchy.cs#L9

```
var statusHierarchy = new List<Status>() {
            Status.Fatal,
            Status.Fail,
            Status.Error,
            Status.Pass,
            Status.Warning,
            Status.Skip,
            Status.Info,
            Status.Debug
};
extent.Config.StatusConfigurator.StatusHierarchy = statusHierarchy;
```

**Comment by pradeipp** [comment]
Hello @anshooarora, thank you for implementing this feature. The syntax you provided doesn't seem to work anymore and I can't find this config either. Where can I find this configuration? I'm using ExtentReports 4 for c#.

**Comment by anshooarora** [comment]
@pradeipp That's correct, it will only impact the test status and not change status for events.

**Comment by pradeipp** [comment]
Hi @anshooarora sorry but I think you didn't see the first part of my question. I cannot find this StausConfigurator property in any of the 3 objects(ExtentReports, ExtentHTMLReporter, ExtentTests). Where can I find this? 
I do see this class in the source code but couldn't figure out how to implement it. 
Thank you for replying promptly

**Comment by pradeipp** [comment]
@anshooarora do you have any new nuget release planned for near future, that would contain this feature? if not is there a way I can get hands on this ?
