### ISSUE TITLE
Template compilation error when executing flush

### ISSUE THREAD

**Issue by idogcode** [extent-framework/extentreports-csharp#57]
Whenever I execute the ExtentReport.flush() method I get en exception regarding references.

I have downloaded the package using NuGet and I don't have issues compiling the code. In another test project, it works fine. I copied the test code to the current project and nothing works.

> RazorEngine.Templating.TemplateCompilationException HResult=0x80131500 Message=Errors >while compiling a Template.
>Please try the following to solve the situation:

>If the problem is about missing/invalid references or multiple defines either try to load the >missing references manually (in the compiling appdomain!) or Specify your references manually >by providing your own IReferenceResolver implementation. See >https://antaris.github.io/RazorEngine/ReferenceResolver.html for details. Currently all >references have to be available as files!
>If you get 'class' does not contain a definition for 'member': try another modelType (for >example 'null' to make the model dynamic). NOTE: You CANNOT use typeof(dynamic) to make >the model dynamic! Or try to use static instead of anonymous/dynamic types. More details >about the error:
>error: (15, 11) The type or namespace name 'AventStack' could not be found (are you missing a >using directive or an assembly reference?)
>error: (16, 11) The type or namespace name 'AventStack' could not be found (are you missing a >using directive or an assembly reference?)
>error: (17, 11) The type or namespace name 'RazorEngine' could not be found (are you missing >a using directive or an assembly reference?)
>error: (18, 11) The type or namespace name 'RazorEngine' could not be found (are you missing >a using directive or an assembly reference?)
>error: (21, 65) The type or namespace name 'RazorEngine' could not be found (are you missing >a using directive or an assembly reference?)
>error: (21, 101) The type or namespace name 'AventStack' could not be found (are you missing >a using directive or an assembly

That is the code I wrote:
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using System.Configuration;
using System.IO;
using System.Diagnostics;
using AutomationClientProduct;
using AutomationReporter;
using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;

static class Program
{

    [STAThread]
    static void Main(string[] args)
    {
        ExtentHtmlReporter reporter = new 
        ExtentHtmlReporter(@"C:\TestResults\result.html");
        ExtentReports reports = new ExtentReports();
        reports.AttachReporter(reporter);
        var logger = reports.CreateTest("New test");
        logger.Pass("Success");
        logger.Info("Succeeded test");
        logger = reports.CreateTest("Second Test");
        logger.Fail("test failed");
        reports.Flush();
}`

**Comment by anunay1** [comment]
I am also facing the same issue, can anyone please help

**Comment by idogcode** [comment]
I managed to solve it by going to the working project debug folder and copying the
web razor and exterreports .dll and .xml files

**Comment by idogcode** [comment]
But I don't know did this happen.
Hopefully one of the developers can shine some light on the subject

**Comment by anunay1** [comment]
yes it was working for me also, but all of a sudden it stopped working, lets hope the shred some ligh quick

**Comment by anunay1** [comment]
I get all the files generated in Debug folder still, i get the same error.
