### ISSUE TITLE
MongoDB packages v2.8.1 break ExtentReports

### ISSUE THREAD

**Issue by misterjunio** [extent-framework/extentreports-csharp#58]
I recently updated my NuGet packages and ran into a run-time error when creating a report with `new ExtentReports()`. It seems that although I updated the `MongoDB.Bson`, `MongoDB.Driver` and `MongoDB.Driver.Core` packages to the latest stable version (2.8.1), `ExtentReports` is still looking for the 2.7.2 version.

According to the `ExtentReports` package info, it should work with any version of the MongoDB packages >=2.7.2, so I am wondering why it is instead directly tied to the 2.7.2 ones

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'MongoDB.Bson, Version=2.7.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=ExtentReports
```

**Comment by anshooarora** [comment]
The upcoming pre-release version fixes this.

**Comment by anshooarora** [comment]
Please check with 4.1.0-alpha.  

Nuget:  https://www.nuget.org/packages/ExtentReports/4.1.0-alpha
