### ISSUE TITLE
Is there a way to use Table Markup in BDD style?

### ISSUE THREAD

**Issue by quan612** [extent-framework/extentreports-csharp#66]
Hi,

I am using ExtentReport 4.03 .net environment.

I am using HTML reporter, and use createTest, creadeNode to export in BDD style. I am wondering if there is a way to instead of logging the table into step based on the scenario info. Something like:

var feature = extent.CreateTest<Feature>("Refund item");
var scenario = feature.CreateNode<Scenario>("Jeff returns a faulty microwave");

Then:
String[][] data = {
    { "Header1", "Header2", "Header3" },
    { "Content.1.1", "Content.2.1", "Content.3.1" },
    { "Content.1.2", "Content.2.2", "Content.3.2" },
    { "Content.1.3", "Content.2.3", "Content.3.3" },
    { "Content.1.4", "Content.2.4", "Content.3.4" }
};
var m = MarkupHelper.CreateTable(data);

var subScenarioDetail = scenario.createNode<Scenario>(m)

Right now, if i don't use createNode BDD style, and use normal extentTest.Log() instead for the whole test, the table is exported normally.

**Comment by anshooarora** [comment]
You can do this:

```
string[][] data =  {
                new string[] { "Header1", "Header2", "Header3" },
                new string[] { "Content.1.1", "Content.2.1", "Content.3.1" },
                new string[] { "Content.1.2", "Content.2.2", "Content.3.2" },
                new string[] { "Content.1.3", "Content.2.3", "Content.3.3" },
                new string[] { "Content.1.4", "Content.2.4", "Content.3.4" }
};
var m = MarkupHelper.CreateTable(data);
extent.CreateTest("First", m.GetMarkup()).Pass("Pass").AssignCategory("Tag");
```
