### ISSUE TITLE
Not supporting for .Net Core 2.1

### ISSUE THREAD

**Issue by pardhu369** [extent-framework/extentreports-csharp#68]
Not supporting for .Net Core 2.1. Please tell the workaround for using this.

I am facing the issue when using .Flush() and also while adding the package it is throwing the warning as 
Severity    Code    Description    Project    File    Line    Suppression State
Warning    NU1701    Package 'ExtentReports 4.0.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

**Comment by anshooarora** [comment]
@pardhu369 Please try with the latest available v5 build (current alpha-5).  It is created with .NET Standard 2.0 so it would support the version you've specified along with all other versions as indicated in [this chart](https://www.extentreports.com/docs/versions/5/net/index.html#combine-multiple-reports).
