### ISSUE TITLE
C# Beta V4 - Issues

### ISSUE THREAD

**Issue by ishah09** [extent-framework/extentreports-csharp#7]
I have found such issues, so attaching C# Nunit test(.cs) as well as html(s). If there are something mismatch in my implementation please correct me. 

Issue-1 : **Report name (.html) is not applying.** Every time, it is creating index.html and dashboard.html and overriding it. 
If this is something new approach, And if there is some way to achieve it, Please correct me. We are needed to be have all reports with unique names. 

Issue-2 : **Dark theme is not working.** 
Implemented as :  `htmlreport.Config.Theme = Theme.Dark;`

Issue-3 : **Report name is not working**
Implemented as :  `htmlreport.Config.ReportName="This is Report name";`

Issue-4 : **Markup Color is not working.** (It has changed with font style-font but color did not applied)
Implemented as :  `test.Pass(MarkupHelper.CreateLabel("This is Hello Text with Markup", ExtentColor.Blue));`

Issue-5 : **Timeline property as True is not working**
Implemented as :  `htmlreport.Config.EnableTimeline = true;`
As of now, By default without declaring above property, Timeline is showing which does not mean. If we want to hide it, we can declare it as false. As like such other things, to use any thing we have to declare it. So as if we are not declaring timeline property as true or false, it should not display on dashboard. If we declare it as true then only it should show. 

Issue-6 : UI issue with Duration box, Timeline watch displays out of Section box
![image](https://user-images.githubusercontent.com/32862749/50630347-83926100-0f66-11e9-9856-3a3a58cc8afb.png)

Query: Earlier image thumbnail was showing in log, now it is showing as img label. Please confirm this is something has been changed. 

Earlier: 

![image](https://user-images.githubusercontent.com/32862749/50627015-8cc80180-0f57-11e9-8b33-6dfdcd680731.png)

New:

![image](https://user-images.githubusercontent.com/32862749/50627025-9baeb400-0f57-11e9-9577-96493d7ef1db.png)

Suggestion: It would be great to have some more documentation on configuration part as well as the method and interface usage. It seems like many things are added, but we might don't know its usage.

**Comment by ishah09** [comment]
[Test-ExtentReport.zip](https://github.com/extent-framework/extentreports-csharp/files/2723197/Test-ExtentReport.zip)

**Comment by anshooarora** [comment]
@ishah09 

1. What you are seeing is the new default Html reporter for version 4. This defaults to 4 templates: index.html, dashboard.html, tag.html and exception.html.  Because each view is broken-down to its own file, we can ensure the overall responsive is much better than version 3.  If you would like to use the old reporter, use `ExtentV3HtmlReporter`.

```java
// arg:directory
var html = new ExtentHtmlReporter("extent/html/");

// arg:file
var v3html = new ExtentV3HtmlReporter("extent/v3html/Extent.html");
```
2. Dark theme is not yet available, but we will add it for the next beta

3. Will fix this for the upcoming beta

4. Will fix this for upcoming beta

5. This is the default for all our reporters now.. 

6. Will fix for upcoming beta

7. I will change this setting to allow thumbnails instead of label

**Comment by anshooarora** [comment]
I am closing this ticket as multiple issues have been raised.  

Refer #10, #11 & #12.

**Comment by sandikumar3** [comment]
@anshooarora ,Unable to implement report for multiple classes with the concept of initializing extentreport object in base class and further inheriting Base class in [TestFixture] classes. Only Last test gets logged.
Kindly assist on this.

**Comment by gauravbh88** [comment]
For me also same thing is happening. 

Unable to implement report for multiple classes with the concept of initializing extentreport object in base class and further inheriting Base class in [TestFixture] classes. Only Last test gets logged.
@anshooarora   Do you have any update on this?

**Comment by anshooarora** [comment]
@sandikumar3 
@gauravbh88 

All - this happens due to incorrect usage. Each test must be a brand new instance, so `CreateTest` or `CreateNode` must be called before a test starts.  Please share your usage.

**Comment by gauravbh88** [comment]
I have attached my usage. 

I have a brand new instance of create test in both test class still one overwrites other in the report.

[sampleTest.zip](https://github.com/extent-framework/extentreports-csharp/files/4102251/sampleTest.zip)

**Comment by anshooarora** [comment]
Use something like below to ensure a single instance is created:

```
public class ExtentManager
{
    private static readonly Lazy<ExtentReports> extent = new Lazy<ExtentReports>(() => new ExtentReports());

    public static ExtentReports I
    {
        get
        {
            return extent.Value;
        }
    }

    private ExtentManager() { }
}
```

New `BaseClass` impl:

```
public class BaseTest
{
    public IWebDriver driver;
   
    [OneTimeSetUp]
    public void Open()
    {

        driver = new ChromeDriver();
        driver.Manage().Window.Maximize();
        driver.Url = "https://test.komplettbank.no/";
        if (extent.Value.StartedReporterList.Count == 0) {
            ExtentV3HtmlReporter htmlReporter = new ExtentV3HtmlReporter("C:\\Users\\Gaurav\\source\\repos\\sampleTest\\sampleTest\\ExtentReport\\extent.html");
            ExtentManager.I.AttachReporter(htmlReporter);
        }
    }

    [OneTimeTearDown]
    public void close()
    {
        ExtentManager.I.Flush();    
    }


    public static string Capture(IWebDriver driver, string ScreenShotName)
    {
        ITakesScreenshot ts = (ITakesScreenshot)driver;
        Screenshot screenshot = ts.GetScreenshot();
        string path = System.Reflection.Assembly.GetCallingAssembly().CodeBase;
        string uptobinPath = path.Substring(0, path.LastIndexOf("bin")) + ScreenShotName + ".png";
        string localpath = new Uri(uptobinPath).LocalPath;
        screenshot.SaveAsFile(localpath, ScreenshotImageFormat.Png);
        return localpath;
    }
}
```
