### ISSUE TITLE
Issues using ExtentReports.Core v1.0.2

### ISSUE THREAD

**Issue by galenyjl** [extent-framework/extentreports-csharp#70]
Hi, I am using .NET Core 2.2 with ExtentReports.Core v1.0.2 and find two issues as follows:
1. Time is covered if the feature name is long
![image](https://user-images.githubusercontent.com/23353422/67442047-c0e1ef80-f65b-11e9-8bea-76c9ab28ee4f.png)
The time should not be covered by text

2. The same feature with multiple scenarios display more than one time
![image](https://user-images.githubusercontent.com/23353422/67442091-ef5fca80-f65b-11e9-868e-8432259a35f8.png)
The same feature should display only one time on the left panel, and multiple scenarios on the right panel

Appreciate any feedback, thanks.

**Comment by anshooarora** [comment]
Hello - this version is provided by the SimplyTest team:  https://github.com/simplytest/extentreports-csharp.  I can fix this issue in the core-API for now, but it will not be automatically implemented in the version you are using.

**Comment by anshooarora** [comment]
The official .NET core build will be available soon.  Initial commit in the following branch now:  https://github.com/extent-framework/extentreports-csharp/tree/net-core

**Comment by anshooarora** [comment]
Issues in this post has been fixed.

**Comment by galenyjl** [comment]
Thanks! @anshooarora
