### ISSUE TITLE
In extent version 4.0.3.0 , i am trying to log pass step with screenshot but in report screenshot size is displayed small. How to enlarge screenshot size and display in next line. 

### ISSUE THREAD

**Issue by KalyaniThosar** [extent-framework/extentreports-csharp#71]
**problem 2 :** when extent report is downloaded from nuget manager, extent-config.xml is not downloaded. How to get config.xml.

**problem 3** : in report version 4.0.3.0, two reports are generated , index.html and dashboard.html,but i want only one report which was generated till version 3.

**tried solution for problem 3** : I tried creating object of ExtentV3HtmlReporter and generating report. In this case only one report was generated , but screenshot size is displayed.

problem 4 : When report is opened in IE browser, screenshot logged in test step is not displayed. But the same report when opened in chromebrowser scrersnhot is displayed.
Since my selenium scripts runs on IE browser , so report is default displayed with IE as my default browser saved is IE.
Is there any way to default store report with Chrome.

` 
public static class ExtentReporting
    {
        static string Screenshot = null;
        public static void Success(this ExtentTest Test, string PassDetails, MediaEntityModelProvider provider = null)
        {
            try
            {
                Screenshot = TakeScreenshot.ScreenshotOfTestStep();
                if (Screenshot != null)
                {
                   var m = MediaEntityBuilder.CreateScreenCaptureFromPath(Screenshot).Build();
                    Test.Pass(PassDetails , m);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
`

**Comment by anshooarora** [comment]
1 - it can be done using CSS, look at the image classes in HTML
2 - will add config examples to the distribution
3 - Yes, the new reporters generate a file for each view, this keeps the file size smaller but I will provide SPA style views in the next major release
    V3Reporter is SPA style, and legacy, port from version 3.  Not sure what the issue here is?
4 - IE, or Edge?
