### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by bakgaard** [extent-framework/extentreports-csharp#73]
* ``LogStatus`` is now just ``Status``
* ``LoadConfig`` no longer exist, and I can't find a replacement for it.
* ``StartTest`` is now ``CreateTest``
* ``EndTest`` is *maybe* ``RemoveTest``?

**Comment by anshooarora** [comment]
* LogStatus is now just Status - Yes
* LoadConfig no longer exist, and I can't find a replacement for it - please see here: http://extentreports.com/docs/versions/4/net/html-reporter.html#configuration
* StartTest is now CreateTest - Yes
* EndTest is maybe RemoveTest? - `EndTest` is no longer required, `RemoveTest` will remove the test and prevent it from appearing in the report
