### ISSUE TITLE
Display execution time by Tag on Dashboard

### ISSUE THREAD

**Issue by naveenmails** [extent-framework/extentreports-csharp#75]
Recently updated from 3 to 4 and appreciate all the new features. We added tags so we could see their status on dashboard. One thing we noticed and would request having is -  execution time by tag on dashboard.

**Comment by anshooarora** [comment]
This is now included in version 5 (currently in alpha-5).  Nuget link: https://www.nuget.org/packages/ExtentReports/5.0.0-alpha5
