### ISSUE TITLE
Could not integrate/merge multiple extent reports into one single report in C#, extent report v3

### ISSUE THREAD

**Issue by thagp01** [extent-framework/extentreports-csharp#77]

**Comment by anshooarora** [comment]
Version 3 is no longer supported..  and this feature is not available in version 4 due to several new reporters being introduced with each having its own nuances.  I do plan to add this feature back, but it will be in version 5 with no ETA as of now.

**Comment by swinslade** [comment]
Hi @anshooarora is there any plans to incorporate this in to future .net versions? 
I use Azure Dev Ops to distribute my selenium/specflow tests across multiple VMs. I am currently using ExtentReports to generate reports files on each machine - which I then gather up at the end of the run and publish. It would be a great feature to be able to merge these reports in to one, either via a command line/script that could be run at the final stage.

**Comment by MartinK-68** [comment]
Hi @anshooarora - I'm also interested in how to merge extent reports across multiple vm's into one ExtentReport. Is it possible?
