### ISSUE TITLE
Gherkin keywords don't appear in the extent report

### ISSUE THREAD

**Issue by Duke482132** [extent-framework/extentreports-csharp#78]
I am appending my steps to a given scenario, despite passing step type it is not being rendered in the report:

    private static ExtentTest _extentScenario;
    ....
    [AfterStep]
    public void AfterStep(ScenarioContext scenarioContext)
    {
           var stepType = ScenarioStepContext.Current.StepInfo.StepDefinitionType.ToString();
           var scenarioStepContext = scenarioContext.StepContext;
           _extentScenario.CreateNode(new GherkinKeyword(stepType), scenarioStepContext.StepInfo.Text); //step type has correct value

enforcing the step type also doesn't do anything

    _extentScenario.CreateNode<Given>(scenarioStepContext.StepInfo.Text);

This is what I get, but I expect to `Given,When,Then,And` to be rendered.

[![enter image description here][1]][1]

and this is what I want:

[![enter image description here][2]][2]

Furthermore we can see that proper classes are added:

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/U3ucA.png
  [2]: https://i.stack.imgur.com/JearQ.png
  [3]: https://i.stack.imgur.com/Ce96Z.png

**Comment by anshooarora** [comment]
The fix will be part of the next release.
