### ISSUE TITLE
Both AddScreenCaptureFromBase64String and AddScreenCaptureFromPath do nothing.

### ISSUE THREAD

**Issue by Duke482132** [extent-framework/extentreports-csharp#79]
I try to add a screenshot to the report, both: `AddScreenCaptureFromBase64String` and `AddScreenCaptureFromPath` do nothing, don't throw any exception either.

    if (scenarioContext.TestError == null)
            {
                var stepNode = _extentScenario.CreateNode(new GherkinKeyword(stepType), scenarioStepContext.StepInfo.Text);
                var screenshot = ReportingUtils.TakeScreenshot(driver);
                stepNode.AddScreenCaptureFromBase64String(screenshot.AsBase64EncodedString, "aTitle");
            }
            else
            {
                var message = scenarioContext.TestError.Message + '\n' + scenarioContext.TestError.InnerException;
                _extentScenario.CreateNode(new GherkinKeyword(stepType), scenarioStepContext.StepInfo.Text)
                    .Fail(message);
            }

No screenshot is being added to the report, the step itself is added correctly besides the keywords as reported in the previous issue.

As I inspected the code, adding screenshot causes this to execute:

        internal void AddScreenCapture(Test test, ScreenCapture screenCapture)
        {
            StarterReporterList.ForEach(x => x.OnScreenCaptureAdded(test, screenCapture));
        }

but `OnScreenCaptureAdded` is empty for the `ExtentHtmlReporter` so does the community version support screenshots at all?

**Comment by anshooarora** [comment]
@Duke482132 The lines below:

```
Assert.That(File.Exists(aPath)); //it does
_extentScenario.AddScreenCaptureFromPath(aPath, "aTitle");
```

do not represent the path correctly in relation to the report.  Even though the image may be available relatively to your project, it may not be present relatively to the report.  I would recommend saving the image relative to the report instead of the project.

**Comment by Duke482132** [comment]
@anshooarora I'll do it however that's not the point, it's just second example of `AddScreenshot` type method that does nothing(they later invoke the same code). It seems that `OnScreenCaptureAdded` is empty for `ExtentHtmlReporter` it should at least thrown `NotImplementedException`. So the screenshots never worked for `ExtentHtmlReporter`, do I imiss something and inserting the image is implemented in different place?

**Comment by anshooarora** [comment]
I do not think you have gone through the code in its entirety as your statement is invalid.  Each reporter can implement the hooks differently, for example, KlovReporter uses this hook:

See here for example:  https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Reporter/ExtentKlovReporter.cs#L300

But FileReporters such as Html do not.  They only care for aggregates as when the file is written, it requires the entire domain to be passed to it.  See here:  https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Reporter/ExtentHtmlReporter.cs#L28

Regarding the issue, logically, a scenario on its own does nothing other than bind and implement steps.  So instead of attaching a screencapture to a scenario, try attaching it to a step (given, when, then, but etc.) and see if it shows up then>

**Comment by Duke482132** [comment]
> I do not think you have gone through the code in its entirety as your statement is invalid. Each reporter can implement the hooks differently, for example, KlovReporter uses this hook:
> 
> See here for example: https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Reporter/ExtentKlovReporter.cs#L300
> 
> But FileReporters such as Html do not. They only care for aggregates as when the file is written, it requires the entire domain to be passed to it. See here: https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Reporter/ExtentHtmlReporter.cs#L28
> 
> Regarding the issue, logically, a scenario on its own does nothing other than bind and implement steps. So instead of attaching a screencapture to a scenario, try attaching it to a step (given, when, then, but etc.) and see if it shows up then?

I've seen KlovReporter code but I marked in the first post that I ask about `ExtentHtmlReporter`. See last line, again I changed code to add the screenshot to the step but nothing happens.... so to make it clear.

Does HTML reporter supports adding screenshots or not? (Yes/No) If yes where is the code for that cause it doesn't do the job? If not, then the proper methods shouldn't be empty but throw the not implemented exception or unsupported exception not just do nothing.

**Comment by anshooarora** [comment]
See here:  

https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Views/Html/Partials/SparkStepDetails.cshtml#L15

This line is invoked from:

https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Views/Html/Partials/SparkBDD.cshtml#L42

Screen capture is used for the lowest level here so changing it to step should work. In your HTML, does the screen shot link not show up in devtools even though the image is not being displayed?

**Comment by Duke482132** [comment]
https://github.com/extent-framework/extentreports-csharp/blob/master/ExtentReports/Views/Html/Partials/SparkStepDetails.cshtml#L15
it iterates through `Model.LogContext.All()` I don't create logger anywhere or add anything to logs, I added a screenshot to an object of `ExtentTest` class which represents a step -> I have edited first post.

Screenshots are not in the DOM at all and I think they're lost in this method:

            private void CopyContextInfoToObservable(Test test)
        {
            //missing check for screenshot
            /*if (test.HasScreenCapture)
               do something  
            }
            */
            if (test.HasAuthor)
            {
                test.AuthorContext.All().ToList()
                    .ForEach(x => AuthorContext.AddAttributeContext((Author)x, test));
            }
            if (test.HasCategory)
            {
                test.CategoryContext.All().ToList()
                    .ForEach(x => CategoryContext.AddAttributeContext((Category)x, test));
            }
            if (test.HasDevice)
            {
                test.DeviceContext.All().ToList()
                    .ForEach(x => DeviceContext.AddAttributeContext((Device)x, test));
            }
            if (test.HasException)
            {
                test.ExceptionInfoContext.All().ToList()
                    .ForEach(x => ExceptionInfoContext.AddAttributeContext((ExceptionInfo)x, test));
            }
            if (test.HasChildren)
            {
                test.NodeContext.All().ToList()
                    .ForEach(x => CopyContextInfoToObservable(x));
            }
        }

**Comment by anshooarora** [comment]
Can you share a barebones snippet that reproduces this issue?  I will check today.

**Comment by Duke482132** [comment]
I have added support for screenshots. I am not sure if I am allowed to contribute to an external Open Source project. If yes, would implementation that produces such a result would be considered in a PR?

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/fpx4k.png
