### ISSUE TITLE
ExtentReports integration for Xamarin (aka Visual Studios for MAC)   

### ISSUE THREAD

**Issue by Moshex** [extent-framework/extentreports-csharp#83]
I have a question about ExtentReports working on a mac. I have a mobile automation project using Xamarin that I tried to integrate ExtentReports into. I got the lates ExtentReports packages(4.0.3) using VS for mac and generated a "Hooks" file to support the ExtentReports. I had no build errors, however, the reports would not get generated. 
This is with a project that uses NUnit 3.0.0 with spec flow version 2.4.1  and the latest Xamarin UI test  package (3.0.5)
Now I tried to do research on whether ExtentReports can be integrated with a Xamarin mobile automation project or not and have not found much or any documentation out there that says it can be done.

My 1st question is can ExtentReports be integrated on a MAC using Xamarin and if yes what are some things that I need to do in order to get it running versus on a windows PC? like is there ExtentReports package versions or something else that I should be aware of?

if not is there any hope to get ExtentReports support for mac? I would love to be able to use it in my project.

My final point that has a question in it, I have an another mobile automation project that does have ExtentReports integrated that does seem to have ExtentReports even on a mac, however, the way that was done was kind of a hacky solution. What was done was that they took the project and converted into a windows project were on the windows pc they integrated the ExtentReports and it worked as intended on windows. Once the project was brought back to a mac the project still ran the test and generated an ExtentReport even on a mac. Now there are some stability issues with the project but overall it works as intended, does this a solution that makes sense in the long run or can this cause issues down the line if ExtentReports is not supported for mac? and is this the only way that you could have ExtentReports on a Xamarin mobile automation project? 

Thank you in advance for your help!

**Comment by anshooarora** [comment]
@Moshex I am currently working on the .NET Core implementation, and the source is available here:  https://github.com/extent-framework/extentreports-csharp/tree/net-core.  I need to run a few tests and expect to deploy the pre-release version by early next week.  You will use the .Net Core version instead of .Net Framework to get this to work as expected.

**Comment by Moshex** [comment]
@anshooarora  That is really cool thank you so much! I am looking forward to it.

**Comment by anshooarora** [comment]
You can use ExtentReports.Core as well.  This package is maintained by SimplyTest team.

**Comment by Moshex** [comment]
@anshooarora So that is not the package you are working on, will your code be available in the NuGet package manager by the end of the week?

**Comment by anshooarora** [comment]
@Moshex Please try with:  https://www.nuget.org/packages/ExtentReports/4.1.0-alpha

Note: this also makes the default HtmlReporter a SPA view.

**Comment by Moshex** [comment]
@anshooarora I added the package you have in the link and it added a bunch more packages with it is that by design?
This is what was added:
  <package id="Crc32C.NET" version="1.0.5.0" targetFramework="net461" />
  <package id="DnsClient" version="1.2.0" targetFramework="net461" />
  <package id="ExtentReports" version="4.1.0-alpha" targetFramework="net461" />
  <package id="Microsoft.AspNetCore" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Authentication.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Authentication.Core" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Connections.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Diagnostics" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Diagnostics.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.HostFiltering" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Hosting" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Hosting.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Hosting.Server.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Html.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Extensions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Features" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.HttpOverrides" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Razor" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Razor.Language" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Razor.Runtime" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Routing" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Routing.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Server.IIS" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Server.IISIntegration" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Server.Kestrel" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Server.Kestrel.Core" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Server.Kestrel.Https" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.WebUtilities" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Common" version="2.8.0" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="2.8.0" targetFramework="net461" />
  <package id="Microsoft.CSharp" version="4.5.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.CommandLine" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.FileExtensions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Json" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.UserSecrets" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Hosting.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Configuration" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Console" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Debug" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.EventSource" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.ObjectPool" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options.ConfigurationExtensions" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.Net.Http.Headers" version="2.2.0" targetFramework="net461" />
  <package id="MongoDB.Bson" version="2.10.0" targetFramework="net461" />
  <package id="MongoDB.Driver" version="2.10.0" targetFramework="net461" />
  <package id="MongoDB.Driver.Core" version="2.10.0" targetFramework="net461" />
  <package id="MongoDB.Libmongocrypt" version="1.0.0" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="12.0.3" targetFramework="net461" />
  <package id="RazorEngine.NetCore" version="2.2.6" targetFramework="net461" />
  <package id="SharpCompress" version="0.23.0" targetFramework="net461" />
  <package id="Snappy.NET" version="1.1.1.8" targetFramework="net461" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net461" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net461" />
  <package id="System.Collections" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Immutable" version="1.5.0" targetFramework="net461" />
  <package id="System.ComponentModel.Annotations" version="4.5.0" targetFramework="net461" />
  <package id="System.Console" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.5.0" targetFramework="net461" />
  <package id="System.Diagnostics.FileVersionInfo" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.StackTrace" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net461" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Pipelines" version="4.5.2" targetFramework="net461" />
  <package id="System.Linq" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Memory" version="4.5.1" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net461" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Emit" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Metadata" version="1.6.0" targetFramework="net461" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.1" targetFramework="net461" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.AccessControl" version="4.5.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Cng" version="4.5.0" targetFramework="net461" />
  <package id="System.Security.Permissions" version="4.5.0" targetFramework="net461" />
  <package id="System.Security.Principal.Windows" version="4.5.0" targetFramework="net461" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding.CodePages" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encodings.Web" version="4.5.0" targetFramework="net461" />
  <package id="System.Threading" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.1" targetFramework="net461" />
  <package id="System.Threading.Tasks.Parallel" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Thread" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XPath" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XPath.XDocument" version="4.3.0" targetFramework="net461" />

**Comment by Moshex** [comment]
@anshooarora I have integrated the package you have suggested with a hooks file and I am still not getting the report to generate when running the tests via the ide is there something I am missing?

**Comment by anshooarora** [comment]
@Moshex The other packages are dependencies to allow .NET Standard library to be integrated with your project.  

Please share your usage, its hard to know what's going on without looking at your code.

**Comment by Moshex** [comment]
@anshooarora I was talking with a DEV and he has a theory that since my project is pointed to .NET Framework 4.6.1  on a MAC that might be the issue, in your experience should that make your code not compatible with my project? 
![Screen Shot 2020-01-28 at 1 39 02 PM](https://user-images.githubusercontent.com/6087936/73303886-7204a280-41d4-11ea-9846-c45862ace722.png)

**Comment by anshooarora** [comment]
.NET Standard is compatible with all .NET distributions.  See here:  https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/september/net-standard-demystifying-net-core-and-net-standard

**Comment by Moshex** [comment]
@anshooarora  That is true However Specflow is not compatible .NET Standard but it is with .NET Core. So just to make sure in order to have both ExtentReports and specflow on a mac your project will need to be a .NET Core as of 02-04-2020. There is talk about Specflow being compatible .NET Standard but right now that is not the case. Could you confirm this being the case, is there something I am missing?

**Comment by anshooarora** [comment]
Can you point me to the discussion?  

Also, what is your version of Xamarin?

**Comment by Moshex** [comment]
This is about specflow:  https://github.com/SpecFlowOSS/SpecFlow/issues/1516 

Here is my VS information:

Visual Studio Enterprise 2019 for Mac
Version 8.3.11 (build 1)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)
	Package version: 604000208

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

NuGet
Version: 5.3.0.6192

**Comment by anshooarora** [comment]
Thanks.  

The following table is from Microsoft:  https://docs.microsoft.com/en-us/dotnet/standard/net-standard:

![image](https://user-images.githubusercontent.com/4107384/73774352-adedb980-4738-11ea-9a18-232a94e9d640.png)

Since ExtentReports is written in .NET Standard 2.0, and thus is supported by all .NET Core 2.x+ and Xamarin Mac 3.8+ versions.

I have to do some more research on this.  Will update you soon.

**Comment by Moshex** [comment]
@anshooarora Do you have any updates to this?

**Comment by anshooarora** [comment]
@Moshex I replied to you in another thread, but just for others who happen to visit this page:

Version 5 (currently in alpha) is created to target .NET Standard 2.0 which would provide coverage to most (if not all) TFM's.  If you are using a TFM which is not supported, please raise an enhancement request.
