### ISSUE TITLE
Error: AventStack.ExtentReports.ExtentReports.GherkinDialect.get

### ISSUE THREAD

**Issue by nukalaamar** [extent-framework/extentreports-csharp#87]
Hi Team,
Environment  : .Net, Visual Studio 2019
When I debug my code, I am getting below error at **extent.flush().**

Error: The Target process exited with code 2147943401 while evaluating the function ' AventStack.ExtentReports.ExtentReports.GherkinDialect.get'

Please advise. Thanks

**Comment by anshooarora** [comment]
@nukalaamar Please share the code that I can use to reproduce this issue.

**Comment by nukalaamar** [comment]
Hi Anshoo,
Thanks for the reply. Please see below code.
public class Hooks
    {
        private readonly BrowserContext browserContext;
        private static AventStack.ExtentReports.ExtentReports extent;
        private static ExtentHtmlReporter _extentHtmlReporter;
        private static ExtentTest _feature;
        private static ExtentTest _scenario;
        private static ScenarioContext _scenarioContext;
        private static FeatureContext _featureContext;

        public Hooks(BrowserContext browserContext)
        {
            this.browserContext = browserContext;
        }

        [BeforeTestRun]
        public static void BeforeTestRun()
        {
            _extentHtmlReporter = new ExtentHtmlReporter(@"E:\log");
            extent = new AventStack.ExtentReports.ExtentReports();          
            extent.AttachReporter(_extentHtmlReporter);
        }
        [BeforeFeature]
        public static void BeforeFeatureStart(FeatureContext featureContext)
        {
            if (null != featureContext)
            {
                //_featureContext = featureContext;
                _feature = extent.CreateTest<Feature>(featureContext.FeatureInfo.Title, featureContext.FeatureInfo.Description);
            }
        }

        [BeforeScenario]
        public void BeforeScenarioStart(ScenarioContext scenarioContext)
        {
            browserContext.Initialize();
            if (null != scenarioContext)
            {
                _scenarioContext = scenarioContext;
                _scenario = _feature.CreateNode<Scenario>(scenarioContext.ScenarioInfo.Title, scenarioContext.ScenarioInfo.Description);
            }
        }
        [AfterStep]
        public void AfterEachStep()
        {
            ScenarioBlock scenarioBlock = _scenarioContext.CurrentScenarioBlock;

            switch (scenarioBlock)
            {
                case ScenarioBlock.Given:

                    CreateNode<Given>();
                    break;
                case ScenarioBlock.When:
                    //if (_scenarioContext.TestError != null)
                    //{
                    //    _scenario.CreateNode<When>(_scenarioContext.StepContext.StepInfo.Text).Fail(_scenarioContext.TestError.Message + "\n" + _scenarioContext.TestError.StackTrace);
                    //}

                    CreateNode<When>();
                    break;
                case ScenarioBlock.Then:
                    CreateNode<Then>();
                    break;

                default:

                    CreateNode<And>();
                    break;

            }

        }
        public void CreateNode<T>() where T : IGherkinFormatterModel

        {
            if (_scenarioContext.TestError != null)
            {             
                _scenario.CreateNode<T>(_scenarioContext.StepContext.StepInfo.Text).Fail(_scenarioContext.TestError.Message + "\n" + _scenarioContext.TestError.StackTrace);
                
            }
            else
            {
                _scenario.CreateNode<T>(_scenarioContext.StepContext.StepInfo.Text).Pass("");
            }

        }
        [AfterTestRun]
        public static void AfterTestRun()
        {
            extent.Flush();
        }

        [BeforeFeature("Tag1")]
        public static void BeforeFeature(FeatureContext featureContext)
        {
            Console.WriteLine("BeforeFeature Hook");
        }

        [AfterFeature("Tag1")]
        public static void AfterFeature()
        {
            Console.WriteLine("AfterFeature Hook");
        }      

        [BeforeScenario]
        public static void BeforeScenarioContextInjection(FeatureContext featureContext, ScenarioContext scenarioContext)
        {
            _featureContext = featureContext;
            _scenarioContext = scenarioContext;
        }

        [AfterScenario]
        public void AfterScenario()
        {
            Console.WriteLine("AfterScenario Hook");
            browserContext.Quit();
        }
    }
}

**Comment by nukalaamar** [comment]
I have tried again today and I am getting below exception. Please advise.
**Exception:** System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Web.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'

**Comment by anshooarora** [comment]
Thanks,  which nuget package are you using?

**Comment by nukalaamar** [comment]
Hi 
I have used below. Thanks
 
    <PackageReference Include="ExtentReports.Core" Version="1.0.3" />
    <PackageReference Include="gherkin" Version="6.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.23" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="16.5.0" />
    <PackageReference Include="MongoDB.Bson" Version="2.10.3" />
    <PackageReference Include="MongoDB.Driver" Version="2.10.3" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.10.3" />
    <PackageReference Include="NUnit.Console" Version="3.11.1" />
    <PackageReference Include="NUnit.ConsoleRunner" Version="3.11.1" />
    
    <PackageReference Include="RazorEngine.NetCore" Version="2.2.6" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>    
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />

**Comment by nukalaamar** [comment]
Hi
I have used below. Thanks     
    <PackageReference Include="ExtentReports.Core" Version="1.0.3" />
    
    <PackageReference Include="gherkin" Version="6.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.23" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="16.5.0" />
    <PackageReference Include="MongoDB.Bson" Version="2.10.3" />
    <PackageReference Include="MongoDB.Driver" Version="2.10.3" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.10.3" />
    <PackageReference Include="NUnit.Console" Version="3.11.1" />
    <PackageReference Include="NUnit.ConsoleRunner" Version="3.11.1" />
    
    <PackageReference Include="RazorEngine.NetCore" Version="2.2.6" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>    
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />

**Comment by nukalaamar** [comment]
Hi 
I am using .Net Core  <TargetFramework>**netcoreapp3.1**</TargetFramework>.

**Nuget packages:**
<PackageReference Include="NUnit.Extension.VSProjectLoader" Version="3.8.0" />		
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
    </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ExtentReports.Core" Version="1.0.3" />
	
    <PackageReference Include="gherkin" Version="6.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.23" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="16.5.0" />
    <PackageReference Include="MongoDB.Bson" Version="2.10.3" />
    <PackageReference Include="MongoDB.Driver" Version="2.10.3" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.10.3" />
    <PackageReference Include="NUnit.Console" Version="3.11.1" />
    <PackageReference Include="NUnit.ConsoleRunner" Version="3.11.1" />
    
    <PackageReference Include="RazorEngine.NetCore" Version="2.2.6" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>    
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
  </ItemGroup>
