### ISSUE TITLE
ExtentTest.Fail Method is not set (Status) parameter. 

### ISSUE THREAD

**Issue by namilkimfree** [extent-framework/extentreports-csharp#89]
dotnet core 3.1
package: this repository dotnet core branch and ExtentReports.Core (1.0.3) 
os: Windows 10
project = dotnetcore.NunitTest.Project

`_scenario.CreateNode<Given>(_scenarioContext.StepContext.StepInfo.Text).Fail(_scenarioContext.TestError.InnerException);
`
_scenario.Status is Status.Pass.

![image](https://user-images.githubusercontent.com/44854923/79964334-800d4b00-84c5-11ea-8aa6-eba6ecd19bee.png)

myObj = null;
My test step Assert.That( myObj != null, "Test only fail");

below is hook code
`
  [BeforeFeature()]
        public static void InitalizeFeature(FeatureContext featureContext)
        {
            //Get feature Name
            _featureName = _extent.CreateTest<Feature>(featureContext.FeatureInfo.Title);
        }

        [BeforeScenario]
        public void InitializeScenario()
        {
            ////Create dynamic scenario name
            _scenario = _featureName.CreateNode<Scenario>(_scenarioContext.ScenarioInfo.Title);
        }

        [AfterStep]
        public void InsertReportingSteps()
        {
            var steptype = _scenarioContext.StepContext.StepInfo.StepDefinitionType;

            switch (steptype)
            {
                case StepDefinitionType.Given:
                    StepDefinitionGiven();
                    break;

                case StepDefinitionType.Then:
                    StepDefinitionThen();
                    break;

                case StepDefinitionType.When:
                    StepDefinitionWhen();
                    break;
            }
        }

      

        private ExtentTest CreateScenario(StepDefinitionType stepDefinitionType)
        {
            var scenarioStepContext = _scenarioContext.StepContext.StepInfo.Text;

            switch (stepDefinitionType)
            {
                case StepDefinitionType.Given:
                    return _scenario.CreateNode<Given>(scenarioStepContext);

                case StepDefinitionType.Then:
                    return _scenario.CreateNode<Then>(scenarioStepContext);

                case StepDefinitionType.When:
                    return _scenario.CreateNode<When>(scenarioStepContext);
                default:
                    throw new ArgumentOutOfRangeException(nameof(stepDefinitionType), stepDefinitionType, null);
            }
        }

        private void CreateScenarioFailOrError(StepDefinitionType stepDefinitionType)
        {
            var error = _scenarioContext.TestError;

            if (error.InnerException == null)
            {
                CreateScenario(stepDefinitionType).Error(error.Message);
            }
            else
            {
                CreateScenario(stepDefinitionType).Fail(error.InnerException);
            }
        }

        private void StepDefinitionGiven()
        {
            if (_scenarioContext.TestError == null)
                CreateScenario(StepDefinitionType.Given);
            else
                CreateScenarioFailOrError(StepDefinitionType.Given);
        }

        private void StepDefinitionWhen()
        {
            if (_scenarioContext.TestError == null)
                CreateScenario(StepDefinitionType.When);
            else
                CreateScenarioFailOrError(StepDefinitionType.When);
        }

        private void StepDefinitionThen()
        {
            if (_scenarioContext.TestError == null)
                CreateScenario(StepDefinitionType.Then);
            else
                CreateScenarioFailOrError( StepDefinitionType.Then);
        }

        [AfterTestRun]
        public static void TearDownReport()
        {
            //Flush report once test completes
            _extent.Flush();
        }
`

and 
my step code

` 
[Given(@"""(.*)"" Test(.*) Code)]
        public void GivenTestCode(string categoryCd, int prdId)
        {
            MyClass myObj = null;
            Assert.That(myObj != null, "Test only fail");
        }
`

Is there a way to solve it?

**Comment by namilkimfree** [comment]
my thoughts are

 ```
        public ExtentTest Log (Status status, Exception ex, MediaEntityModelProvider provider = null)
        {
            ExceptionInfo e = new ExceptionInfo (ex);
            Model.ExceptionInfoContext.Add (e);
            var evt = new Log (Model)
            {
                ExceptionInfo = e
            };
            return AddLog (evt);
        }

```
From here
   ```
 var evt = new Log (Model)
            {
                Status = status,
                ExceptionInfo = e
            };

```
It seems that the part of entering the Status value is missing.

**Comment by anshooarora** [comment]
@namilkimfree Can you check with [4.1.0-alpha3](https://www.nuget.org/packages/ExtentReports/4.1.0-alpha3)?

**Comment by namilkimfree** [comment]
@anshooarora    yes, I will check  with 4.1.0-alpha3

**Comment by namilkimfree** [comment]
@anshooarora  
I checked it, but it is the same symptom.

**Comment by namilkimfree** [comment]
@anshooarora  

When you call the Fail (new Exception ("TestException")) method, the status is passed on the dashboard and exception and tests page.

regard please.
thank you

**Comment by anshooarora** [comment]
@namilkimfree this is fixed in version 5 (currently in alpha).  Additional notes from other thread:

> HtmlReporter is deprecated and replaced by SparkReporter; KlovReporter will be a separate release ([here](https://www.nuget.org/packages/klov-reporter/5.0.0-alpha5)); all packages built on .NET Standard 2.0

Docs: https://www.extentreports.com/docs/versions/5/net/index.html
