### ISSUE TITLE
Extent report throwing an exception when trying to flush the report

### ISSUE THREAD

**Issue by mtalreja** [extent-framework/extentreports-csharp#91]
I am using Extent report [v4.0.3] for my C# project [.Net Framework]

When I try to flush the report I got the below exception.
I am using MSTest as a Testing Framework. I call the below code at [Assembly CleanUp] level 

 For extent object creation i use ----  _extent = new ExtentReports();
  ```
      public static void Flush()
        {
            _extent.Flush(); //Here i get an exception
        }
```
Exception:

System.TypeLoadException: 'Inheritance security rules violated by type: 'RazorEngine.Compilation.CSharp.CSharpRazorCodeLanguage'. Derived types must either match the security accessibility of the base type or be less accessible.'

I am struggling to solve the problem and thanks a lot in advance.

**Comment by anshooarora** [comment]
@mtalreja Can you check with [4.1.0-alpha3](https://www.nuget.org/packages/ExtentReports/4.1.0-alpha3)?

**Comment by jvattatharaSN** [comment]
I am using Java project ( not C#) - but I tried with 4.1.0  at Maven ( could not find alpha) https://mvnrepository.com/artifact/com.aventstack/extentreports/4.1.0
 getting following error now:
 java.lang.Error: 
Unresolved compilation problem: 
	VERSION_2_3_29 cannot be resolved or is not a field.

error occurred at code level->reportE.attachReporter(htmlReporter);

**Comment by jvattatharaSN** [comment]
I think this error is a manifestation of selenium - chrome driver mismatch and 
Connection reset
java.net.SocketException: Connection reset.

Will update as we get to the bottom of this-- Thanks for your help!
