### ISSUE TITLE
Extent Reports v3.1.3 AppendExisting does not work

### ISSUE THREAD

**Issue by sundusnisar** [extent-framework/extentreports-csharp#93]
I have a project with 30 tests. I run it and report is generated. If 1 test fails, I only run that failed test again. The new generated report contains only last failed test.
I want to have all 30 tests of first report, with only failed tests replaced with last run test.

Here is the code am using

 var path = System.Reflection.Assembly.GetCallingAssembly().CodeBase;
            var actualPath = path.Substring(0, path.LastIndexOf("bin"));
            var projectPath = new Uri(actualPath).LocalPath;
            var reportPath = projectPath + "Reports\\ExtentReport.html";
            ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter("ExtentReport.html");
            htmlReporter.AppendExisting = true;
            _extent = new ExtentReports();
            _extent.AttachReporter(htmlReporter); 

It makes no difference either I set true or false to htmlReporter.AppendExisting .
Any help is appreciated.

**Comment by anshooarora** [comment]
This feature will be available starting version 5.0.  Please track #97.
