### ISSUE TITLE
Information regarding extent.js file

### ISSUE THREAD

**Issue by pravekdadhwal** [extent-framework/extentreports-csharp#96]
Dear Anshoo,

I hope this email finds you in good health and spirit.

I am using ExtentReport version 3.0.2 and have one question related to **extent.js**. Actually, I am generating a report and sending it to our team through our internal SMTP. Our organization's **Exchange Online Protection** is blocking the attachment file and I have been requested to provide explanation on what https://cdn.rawgit.com/anshooarora/extentreports-csharp/ccd5fe10730e2bf01a55df550baf24882a9cf86f/dist/js/**extent.js** exactly does. Would you be able to provide me a brief description, I assume it's being used to generate the report, but just wanted to confirm with you once.

Best Regards,
Pravek Dadhwal

**Comment by anshooarora** [comment]
@pravekdadhwal This file contains all the JS to enable all the interactiveness from the static HTML file.  If you examine the contents, it has the following libraries:

* jQuery
* jQuery UI
* Materialize
* Chart.js
* Featherlight (lightbox)
* all other JS that is custom to the report file to render:
  * Charts
  * Views
  * Actions (click test/tag to view details etc)

Hope this helps.
